// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package model

import (
	"context"
	"time"
)

const countEntries = `-- name: CountEntries :one
SELECT count(*) FROM entries
`

func (q *Queries) CountEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getEntryByPath = `-- name: GetEntryByPath :one
SELECT id, title, body, formatted_body, path, format, date, created_at, modified_at FROM entries
WHERE path = ? LIMIT 1
`

func (q *Queries) GetEntryByPath(ctx context.Context, path string) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntryByPath, path)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.FormattedBody,
		&i.Path,
		&i.Format,
		&i.Date,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getNextEntry = `-- name: GetNextEntry :one
SELECT id, title, body, formatted_body, path, format, date, created_at, modified_at FROM entries
WHERE created_at > ?
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetNextEntry(ctx context.Context, createdAt time.Time) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getNextEntry, createdAt)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.FormattedBody,
		&i.Path,
		&i.Format,
		&i.Date,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getPrevEntry = `-- name: GetPrevEntry :one
SELECT id, title, body, formatted_body, path, format, date, created_at, modified_at FROM entries
WHERE created_at < ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetPrevEntry(ctx context.Context, createdAt time.Time) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getPrevEntry, createdAt)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.FormattedBody,
		&i.Path,
		&i.Format,
		&i.Date,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const listAllEntriesForSitemap = `-- name: ListAllEntriesForSitemap :many
SELECT path, modified_at FROM entries
ORDER BY date DESC
`

type ListAllEntriesForSitemapRow struct {
	Path       string    `json:"path"`
	ModifiedAt time.Time `json:"modified_at"`
}

func (q *Queries) ListAllEntriesForSitemap(ctx context.Context) ([]ListAllEntriesForSitemapRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllEntriesForSitemap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllEntriesForSitemapRow
	for rows.Next() {
		var i ListAllEntriesForSitemapRow
		if err := rows.Scan(&i.Path, &i.ModifiedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchiveMonths = `-- name: ListArchiveMonths :many
SELECT
	strftime('%Y', date) as year,
	strftime('%m', date) as month,
	count(*) as count
FROM entries
GROUP BY strftime('%Y-%m', date)
ORDER BY date DESC
`

type ListArchiveMonthsRow struct {
	Year  interface{} `json:"year"`
	Month interface{} `json:"month"`
	Count int64       `json:"count"`
}

func (q *Queries) ListArchiveMonths(ctx context.Context) ([]ListArchiveMonthsRow, error) {
	rows, err := q.db.QueryContext(ctx, listArchiveMonths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArchiveMonthsRow
	for rows.Next() {
		var i ListArchiveMonthsRow
		if err := rows.Scan(&i.Year, &i.Month, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntries = `-- name: ListEntries :many
SELECT id, title, body, formatted_body, path, format, date, created_at, modified_at FROM entries
WHERE date <= ?
ORDER BY date DESC, created_at ASC
LIMIT ?
`

type ListEntriesParams struct {
	Date  time.Time `json:"date"`
	Limit int64     `json:"limit"`
}

func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntries, arg.Date, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.FormattedBody,
			&i.Path,
			&i.Format,
			&i.Date,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByCategory = `-- name: ListEntriesByCategory :many
SELECT id, title, body, formatted_body, path, format, date, created_at, modified_at FROM entries
WHERE title LIKE ? AND date <= ?
ORDER BY date DESC, created_at ASC
LIMIT ?
`

type ListEntriesByCategoryParams struct {
	Title string    `json:"title"`
	Date  time.Time `json:"date"`
	Limit int64     `json:"limit"`
}

func (q *Queries) ListEntriesByCategory(ctx context.Context, arg ListEntriesByCategoryParams) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesByCategory, arg.Title, arg.Date, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.FormattedBody,
			&i.Path,
			&i.Format,
			&i.Date,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByYearMonthDay = `-- name: ListEntriesByYearMonthDay :many
SELECT id, title, body, formatted_body, path, format, date, created_at, modified_at FROM entries
WHERE CAST(? AS TEXT) <= date AND date < CAST(? AS TEXT)
ORDER BY created_at
`

type ListEntriesByYearMonthDayParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) ListEntriesByYearMonthDay(ctx context.Context, arg ListEntriesByYearMonthDayParams) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesByYearMonthDay, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.FormattedBody,
			&i.Path,
			&i.Format,
			&i.Date,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
