// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package model

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const countEntries = `-- name: CountEntries :one
SELECT count(*) FROM entries WHERE status = 'public' AND (publish_at IS NULL OR publish_at <= CURRENT_TIMESTAMP)
`

func (q *Queries) CountEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEntriesByDate = `-- name: CountEntriesByDate :one
SELECT count(*) FROM entries WHERE status = 'public' AND (publish_at IS NULL OR publish_at <= CURRENT_TIMESTAMP) AND CAST(date AS TEXT) = ?1
`

func (q *Queries) CountEntriesByDate(ctx context.Context, date string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEntriesByDate, date)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
    title, body, formatted_body, path, format, date, created_at, modified_at, publish_at, status
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10
) RETURNING id, title, body, formatted_body, path, format, date, created_at, modified_at, publish_at, status
`

type CreateEntryParams struct {
	Title         string       `json:"title"`
	Body          string       `json:"body"`
	FormattedBody string       `json:"formatted_body"`
	Path          string       `json:"path"`
	Format        string       `json:"format"`
	Date          string       `json:"date"`
	CreatedAt     time.Time    `json:"created_at"`
	ModifiedAt    time.Time    `json:"modified_at"`
	PublishAt     sql.NullTime `json:"publish_at"`
	Status        string       `json:"status"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry,
		arg.Title,
		arg.Body,
		arg.FormattedBody,
		arg.Path,
		arg.Format,
		arg.Date,
		arg.CreatedAt,
		arg.ModifiedAt,
		arg.PublishAt,
		arg.Status,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.FormattedBody,
		&i.Path,
		&i.Format,
		&i.Date,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.PublishAt,
		&i.Status,
	)
	return i, err
}

const findScheduledEntriesToPublish = `-- name: FindScheduledEntriesToPublish :many
SELECT id, title, body, formatted_body, path, format, CAST(date AS TEXT) AS date, created_at, modified_at, publish_at, status FROM entries
WHERE status = 'scheduled' AND (publish_at IS NULL OR publish_at <= ?1)
ORDER BY publish_at ASC
`

type FindScheduledEntriesToPublishRow struct {
	ID            int64        `json:"id"`
	Title         string       `json:"title"`
	Body          string       `json:"body"`
	FormattedBody string       `json:"formatted_body"`
	Path          string       `json:"path"`
	Format        string       `json:"format"`
	Date          string       `json:"date"`
	CreatedAt     time.Time    `json:"created_at"`
	ModifiedAt    time.Time    `json:"modified_at"`
	PublishAt     sql.NullTime `json:"publish_at"`
	Status        string       `json:"status"`
}

func (q *Queries) FindScheduledEntriesToPublish(ctx context.Context, now sql.NullTime) ([]FindScheduledEntriesToPublishRow, error) {
	rows, err := q.db.QueryContext(ctx, findScheduledEntriesToPublish, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindScheduledEntriesToPublishRow
	for rows.Next() {
		var i FindScheduledEntriesToPublishRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.FormattedBody,
			&i.Path,
			&i.Format,
			&i.Date,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.PublishAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntryById = `-- name: GetEntryById :one
SELECT id, title, body, formatted_body, path, format, CAST(date AS TEXT) AS date, created_at, modified_at, publish_at, status FROM entries
WHERE id = ?1 LIMIT 1
`

type GetEntryByIdRow struct {
	ID            int64        `json:"id"`
	Title         string       `json:"title"`
	Body          string       `json:"body"`
	FormattedBody string       `json:"formatted_body"`
	Path          string       `json:"path"`
	Format        string       `json:"format"`
	Date          string       `json:"date"`
	CreatedAt     time.Time    `json:"created_at"`
	ModifiedAt    time.Time    `json:"modified_at"`
	PublishAt     sql.NullTime `json:"publish_at"`
	Status        string       `json:"status"`
}

func (q *Queries) GetEntryById(ctx context.Context, id int64) (GetEntryByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getEntryById, id)
	var i GetEntryByIdRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.FormattedBody,
		&i.Path,
		&i.Format,
		&i.Date,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.PublishAt,
		&i.Status,
	)
	return i, err
}

const getEntryByPath = `-- name: GetEntryByPath :one
SELECT id, title, body, formatted_body, path, format, CAST(date AS TEXT) AS date, created_at, modified_at, publish_at, status FROM entries
WHERE path = ?1 LIMIT 1
`

type GetEntryByPathRow struct {
	ID            int64        `json:"id"`
	Title         string       `json:"title"`
	Body          string       `json:"body"`
	FormattedBody string       `json:"formatted_body"`
	Path          string       `json:"path"`
	Format        string       `json:"format"`
	Date          string       `json:"date"`
	CreatedAt     time.Time    `json:"created_at"`
	ModifiedAt    time.Time    `json:"modified_at"`
	PublishAt     sql.NullTime `json:"publish_at"`
	Status        string       `json:"status"`
}

func (q *Queries) GetEntryByPath(ctx context.Context, path string) (GetEntryByPathRow, error) {
	row := q.db.QueryRowContext(ctx, getEntryByPath, path)
	var i GetEntryByPathRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.FormattedBody,
		&i.Path,
		&i.Format,
		&i.Date,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.PublishAt,
		&i.Status,
	)
	return i, err
}

const getNextEntry = `-- name: GetNextEntry :one
SELECT id, title, body, formatted_body, path, format, CAST(date AS TEXT) AS date, created_at, modified_at, publish_at, status FROM entries
WHERE status = 'public' AND (publish_at IS NULL OR publish_at <= CURRENT_TIMESTAMP) AND created_at > ?1
ORDER BY created_at ASC
LIMIT 1
`

type GetNextEntryRow struct {
	ID            int64        `json:"id"`
	Title         string       `json:"title"`
	Body          string       `json:"body"`
	FormattedBody string       `json:"formatted_body"`
	Path          string       `json:"path"`
	Format        string       `json:"format"`
	Date          string       `json:"date"`
	CreatedAt     time.Time    `json:"created_at"`
	ModifiedAt    time.Time    `json:"modified_at"`
	PublishAt     sql.NullTime `json:"publish_at"`
	Status        string       `json:"status"`
}

func (q *Queries) GetNextEntry(ctx context.Context, createdAt time.Time) (GetNextEntryRow, error) {
	row := q.db.QueryRowContext(ctx, getNextEntry, createdAt)
	var i GetNextEntryRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.FormattedBody,
		&i.Path,
		&i.Format,
		&i.Date,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.PublishAt,
		&i.Status,
	)
	return i, err
}

const getPrevEntry = `-- name: GetPrevEntry :one
SELECT id, title, body, formatted_body, path, format, CAST(date AS TEXT) AS date, created_at, modified_at, publish_at, status FROM entries
WHERE status = 'public' AND (publish_at IS NULL OR publish_at <= CURRENT_TIMESTAMP) AND created_at < ?1
ORDER BY created_at DESC
LIMIT 1
`

type GetPrevEntryRow struct {
	ID            int64        `json:"id"`
	Title         string       `json:"title"`
	Body          string       `json:"body"`
	FormattedBody string       `json:"formatted_body"`
	Path          string       `json:"path"`
	Format        string       `json:"format"`
	Date          string       `json:"date"`
	CreatedAt     time.Time    `json:"created_at"`
	ModifiedAt    time.Time    `json:"modified_at"`
	PublishAt     sql.NullTime `json:"publish_at"`
	Status        string       `json:"status"`
}

func (q *Queries) GetPrevEntry(ctx context.Context, createdAt time.Time) (GetPrevEntryRow, error) {
	row := q.db.QueryRowContext(ctx, getPrevEntry, createdAt)
	var i GetPrevEntryRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.FormattedBody,
		&i.Path,
		&i.Format,
		&i.Date,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.PublishAt,
		&i.Status,
	)
	return i, err
}

const listAllEntries = `-- name: ListAllEntries :many
SELECT id, title, body, formatted_body, path, format, CAST(date AS TEXT) AS date, created_at, modified_at, publish_at, status FROM entries
ORDER BY date DESC, created_at DESC
`

type ListAllEntriesRow struct {
	ID            int64        `json:"id"`
	Title         string       `json:"title"`
	Body          string       `json:"body"`
	FormattedBody string       `json:"formatted_body"`
	Path          string       `json:"path"`
	Format        string       `json:"format"`
	Date          string       `json:"date"`
	CreatedAt     time.Time    `json:"created_at"`
	ModifiedAt    time.Time    `json:"modified_at"`
	PublishAt     sql.NullTime `json:"publish_at"`
	Status        string       `json:"status"`
}

func (q *Queries) ListAllEntries(ctx context.Context) ([]ListAllEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllEntriesRow
	for rows.Next() {
		var i ListAllEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.FormattedBody,
			&i.Path,
			&i.Format,
			&i.Date,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.PublishAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllEntriesForSitemap = `-- name: ListAllEntriesForSitemap :many
SELECT path, modified_at FROM entries
WHERE status = 'public' AND (publish_at IS NULL OR publish_at <= CURRENT_TIMESTAMP)
ORDER BY date DESC
`

type ListAllEntriesForSitemapRow struct {
	Path       string    `json:"path"`
	ModifiedAt time.Time `json:"modified_at"`
}

func (q *Queries) ListAllEntriesForSitemap(ctx context.Context) ([]ListAllEntriesForSitemapRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllEntriesForSitemap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllEntriesForSitemapRow
	for rows.Next() {
		var i ListAllEntriesForSitemapRow
		if err := rows.Scan(&i.Path, &i.ModifiedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchiveMonths = `-- name: ListArchiveMonths :many
SELECT
	strftime('%Y', date) as year,
	strftime('%m', date) as month,
	count(*) as count
FROM entries
WHERE status = 'public' AND (publish_at IS NULL OR publish_at <= CURRENT_TIMESTAMP)
GROUP BY strftime('%Y-%m', date)
ORDER BY date DESC
`

type ListArchiveMonthsRow struct {
	Year  interface{} `json:"year"`
	Month interface{} `json:"month"`
	Count int64       `json:"count"`
}

func (q *Queries) ListArchiveMonths(ctx context.Context) ([]ListArchiveMonthsRow, error) {
	rows, err := q.db.QueryContext(ctx, listArchiveMonths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArchiveMonthsRow
	for rows.Next() {
		var i ListArchiveMonthsRow
		if err := rows.Scan(&i.Year, &i.Month, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntries = `-- name: ListEntries :many

SELECT id, title, body, formatted_body, path, format, CAST(date AS TEXT) AS date, created_at, modified_at, publish_at, status FROM entries
WHERE status = 'public' AND (publish_at IS NULL OR publish_at <= CURRENT_TIMESTAMP) AND date <= ?1
ORDER BY date DESC, created_at ASC
LIMIT ?2
`

type ListEntriesParams struct {
	TargetDate string `json:"target_date"`
	Limit      int64  `json:"limit"`
}

type ListEntriesRow struct {
	ID            int64        `json:"id"`
	Title         string       `json:"title"`
	Body          string       `json:"body"`
	FormattedBody string       `json:"formatted_body"`
	Path          string       `json:"path"`
	Format        string       `json:"format"`
	Date          string       `json:"date"`
	CreatedAt     time.Time    `json:"created_at"`
	ModifiedAt    time.Time    `json:"modified_at"`
	PublishAt     sql.NullTime `json:"publish_at"`
	Status        string       `json:"status"`
}

// Note: sqlite3 driver converts DATE to time.Time by default, which is undesirable for
// date-based logic here (we want YYYY-MM-DD string). We use CAST(date AS TEXT) to
// ensure string return and we cannot change the schema to TEXT because we reuse
// existing data files.
func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]ListEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntries, arg.TargetDate, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesRow
	for rows.Next() {
		var i ListEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.FormattedBody,
			&i.Path,
			&i.Format,
			&i.Date,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.PublishAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByCategory = `-- name: ListEntriesByCategory :many
SELECT id, title, body, formatted_body, path, format, CAST(date AS TEXT) AS date, created_at, modified_at, publish_at, status FROM entries
WHERE status = 'public' AND (publish_at IS NULL OR publish_at <= CURRENT_TIMESTAMP) AND title LIKE ?1 AND date <= ?2
ORDER BY date DESC, created_at ASC
LIMIT ?3
`

type ListEntriesByCategoryParams struct {
	Title      string `json:"title"`
	TargetDate string `json:"target_date"`
	Limit      int64  `json:"limit"`
}

type ListEntriesByCategoryRow struct {
	ID            int64        `json:"id"`
	Title         string       `json:"title"`
	Body          string       `json:"body"`
	FormattedBody string       `json:"formatted_body"`
	Path          string       `json:"path"`
	Format        string       `json:"format"`
	Date          string       `json:"date"`
	CreatedAt     time.Time    `json:"created_at"`
	ModifiedAt    time.Time    `json:"modified_at"`
	PublishAt     sql.NullTime `json:"publish_at"`
	Status        string       `json:"status"`
}

func (q *Queries) ListEntriesByCategory(ctx context.Context, arg ListEntriesByCategoryParams) ([]ListEntriesByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesByCategory, arg.Title, arg.TargetDate, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesByCategoryRow
	for rows.Next() {
		var i ListEntriesByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.FormattedBody,
			&i.Path,
			&i.Format,
			&i.Date,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.PublishAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByDates = `-- name: ListEntriesByDates :many
SELECT id, title, body, formatted_body, path, format, CAST(date AS TEXT) AS date, created_at, modified_at, publish_at, status FROM entries
WHERE status = 'public' AND (publish_at IS NULL OR publish_at <= CURRENT_TIMESTAMP) AND date IN (/*SLICE:dates*/?)
ORDER BY date DESC, created_at ASC
`

type ListEntriesByDatesRow struct {
	ID            int64        `json:"id"`
	Title         string       `json:"title"`
	Body          string       `json:"body"`
	FormattedBody string       `json:"formatted_body"`
	Path          string       `json:"path"`
	Format        string       `json:"format"`
	Date          string       `json:"date"`
	CreatedAt     time.Time    `json:"created_at"`
	ModifiedAt    time.Time    `json:"modified_at"`
	PublishAt     sql.NullTime `json:"publish_at"`
	Status        string       `json:"status"`
}

func (q *Queries) ListEntriesByDates(ctx context.Context, dates []string) ([]ListEntriesByDatesRow, error) {
	query := listEntriesByDates
	var queryParams []interface{}
	if len(dates) > 0 {
		for _, v := range dates {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:dates*/?", strings.Repeat(",?", len(dates))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:dates*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesByDatesRow
	for rows.Next() {
		var i ListEntriesByDatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.FormattedBody,
			&i.Path,
			&i.Format,
			&i.Date,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.PublishAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByIds = `-- name: ListEntriesByIds :many
SELECT id, title, body, formatted_body, path, format, CAST(date AS TEXT) AS date, created_at, modified_at, publish_at, status FROM entries
WHERE id IN (/*SLICE:ids*/?)
`

type ListEntriesByIdsRow struct {
	ID            int64        `json:"id"`
	Title         string       `json:"title"`
	Body          string       `json:"body"`
	FormattedBody string       `json:"formatted_body"`
	Path          string       `json:"path"`
	Format        string       `json:"format"`
	Date          string       `json:"date"`
	CreatedAt     time.Time    `json:"created_at"`
	ModifiedAt    time.Time    `json:"modified_at"`
	PublishAt     sql.NullTime `json:"publish_at"`
	Status        string       `json:"status"`
}

func (q *Queries) ListEntriesByIds(ctx context.Context, ids []int64) ([]ListEntriesByIdsRow, error) {
	query := listEntriesByIds
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesByIdsRow
	for rows.Next() {
		var i ListEntriesByIdsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.FormattedBody,
			&i.Path,
			&i.Format,
			&i.Date,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.PublishAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByYearMonthDay = `-- name: ListEntriesByYearMonthDay :many
SELECT id, title, body, formatted_body, path, format, CAST(date AS TEXT) AS date, created_at, modified_at, publish_at, status FROM entries
WHERE status = 'public' AND (publish_at IS NULL OR publish_at <= CURRENT_TIMESTAMP) AND CAST(?1 AS TEXT) <= CAST(date AS TEXT) AND CAST(date AS TEXT) < CAST(?2 AS TEXT)
ORDER BY created_at
`

type ListEntriesByYearMonthDayParams struct {
	StartDate string `json:"start_date"`
	EndDate   string `json:"end_date"`
}

type ListEntriesByYearMonthDayRow struct {
	ID            int64        `json:"id"`
	Title         string       `json:"title"`
	Body          string       `json:"body"`
	FormattedBody string       `json:"formatted_body"`
	Path          string       `json:"path"`
	Format        string       `json:"format"`
	Date          string       `json:"date"`
	CreatedAt     time.Time    `json:"created_at"`
	ModifiedAt    time.Time    `json:"modified_at"`
	PublishAt     sql.NullTime `json:"publish_at"`
	Status        string       `json:"status"`
}

func (q *Queries) ListEntriesByYearMonthDay(ctx context.Context, arg ListEntriesByYearMonthDayParams) ([]ListEntriesByYearMonthDayRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesByYearMonthDay, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesByYearMonthDayRow
	for rows.Next() {
		var i ListEntriesByYearMonthDayRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.FormattedBody,
			&i.Path,
			&i.Format,
			&i.Date,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.PublishAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUniqueDates = `-- name: ListUniqueDates :many
SELECT DISTINCT CAST(date AS TEXT) AS date FROM entries
WHERE status = 'public' AND (publish_at IS NULL OR publish_at <= CURRENT_TIMESTAMP) AND date <= ?1
ORDER BY date DESC
LIMIT ?2
`

type ListUniqueDatesParams struct {
	TargetDate string `json:"target_date"`
	Limit      int64  `json:"limit"`
}

func (q *Queries) ListUniqueDates(ctx context.Context, arg ListUniqueDatesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUniqueDates, arg.TargetDate, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var date string
		if err := rows.Scan(&date); err != nil {
			return nil, err
		}
		items = append(items, date)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishEntries = `-- name: PublishEntries :exec
UPDATE entries
SET status = 'public'
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) PublishEntries(ctx context.Context, ids []int64) error {
	query := publishEntries
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE entries SET
    title = ?1,
    body = ?2,
    formatted_body = ?3,
    path = ?4,
    format = ?5,
    date = ?6,
    modified_at = ?7,
    publish_at = ?8,
    status = ?9
WHERE id = ?10
RETURNING id, title, body, formatted_body, path, format, date, created_at, modified_at, publish_at, status
`

type UpdateEntryParams struct {
	Title         string       `json:"title"`
	Body          string       `json:"body"`
	FormattedBody string       `json:"formatted_body"`
	Path          string       `json:"path"`
	Format        string       `json:"format"`
	Date          string       `json:"date"`
	ModifiedAt    time.Time    `json:"modified_at"`
	PublishAt     sql.NullTime `json:"publish_at"`
	Status        string       `json:"status"`
	ID            int64        `json:"id"`
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, updateEntry,
		arg.Title,
		arg.Body,
		arg.FormattedBody,
		arg.Path,
		arg.Format,
		arg.Date,
		arg.ModifiedAt,
		arg.PublishAt,
		arg.Status,
		arg.ID,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.FormattedBody,
		&i.Path,
		&i.Format,
		&i.Date,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.PublishAt,
		&i.Status,
	)
	return i, err
}
