// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: images.sql

package model

import (
	"context"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images (uri, entry_id, sig) VALUES (?, ?, ?) RETURNING id
`

type CreateImageParams struct {
	Uri     string `json:"uri"`
	EntryID int64  `json:"entry_id"`
	Sig     []byte `json:"sig"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createImage, arg.Uri, arg.EntryID, arg.Sig)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createNgram = `-- name: CreateNgram :exec
INSERT OR REPLACE INTO ngram (image_id, word) VALUES (?, ?)
`

type CreateNgramParams struct {
	ImageID int64  `json:"image_id"`
	Word    []byte `json:"word"`
}

func (q *Queries) CreateNgram(ctx context.Context, arg CreateNgramParams) error {
	_, err := q.db.ExecContext(ctx, createNgram, arg.ImageID, arg.Word)
	return err
}

const deleteImagesByEntryID = `-- name: DeleteImagesByEntryID :exec
DELETE FROM images WHERE entry_id = ?
`

func (q *Queries) DeleteImagesByEntryID(ctx context.Context, entryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteImagesByEntryID, entryID)
	return err
}

const deleteNgramsByEntryID = `-- name: DeleteNgramsByEntryID :exec
DELETE FROM ngram WHERE image_id IN (SELECT id FROM images WHERE entry_id = ?)
`

func (q *Queries) DeleteNgramsByEntryID(ctx context.Context, entryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteNgramsByEntryID, entryID)
	return err
}

const deleteNgramsByImageID = `-- name: DeleteNgramsByImageID :exec
DELETE FROM ngram WHERE image_id = ?
`

func (q *Queries) DeleteNgramsByImageID(ctx context.Context, imageID int64) error {
	_, err := q.db.ExecContext(ctx, deleteNgramsByImageID, imageID)
	return err
}

const getImageByURI = `-- name: GetImageByURI :one
SELECT id, uri, entry_id, sig FROM images WHERE uri = ? LIMIT 1
`

func (q *Queries) GetImageByURI(ctx context.Context, uri string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImageByURI, uri)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Uri,
		&i.EntryID,
		&i.Sig,
	)
	return i, err
}

const listImagesByEntryID = `-- name: ListImagesByEntryID :many
SELECT id, uri, entry_id, sig FROM images WHERE entry_id = ?
`

func (q *Queries) ListImagesByEntryID(ctx context.Context, entryID int64) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesByEntryID, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Uri,
			&i.EntryID,
			&i.Sig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSimilarImages = `-- name: ListSimilarImages :many
SELECT
    i.id,
    i.uri,
    i.entry_id,
    COUNT(isw.word) as score
FROM
    images AS i
JOIN 
    ngram AS isw ON i.id = isw.image_id
JOIN 
    ngram AS isw_search ON isw.word = isw_search.word AND isw.image_id != isw_search.image_id
WHERE
    isw_search.image_id = ?
GROUP BY 
    i.id
ORDER BY 
    score DESC
LIMIT ?
`

type ListSimilarImagesParams struct {
	ImageID int64 `json:"image_id"`
	Limit   int64 `json:"limit"`
}

type ListSimilarImagesRow struct {
	ID      int64  `json:"id"`
	Uri     string `json:"uri"`
	EntryID int64  `json:"entry_id"`
	Score   int64  `json:"score"`
}

func (q *Queries) ListSimilarImages(ctx context.Context, arg ListSimilarImagesParams) ([]ListSimilarImagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSimilarImages, arg.ImageID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSimilarImagesRow
	for rows.Next() {
		var i ListSimilarImagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uri,
			&i.EntryID,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
