// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: images.sql

package model

import (
	"context"
	"strings"
)

const countImages = `-- name: CountImages :one
SELECT COUNT(*) FROM images
`

func (q *Queries) CountImages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countImages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createImage = `-- name: CreateImage :one
INSERT INTO images (uri, entry_id, sig) VALUES (?, ?, ?) RETURNING id
`

type CreateImageParams struct {
	Uri     string `json:"uri"`
	EntryID int64  `json:"entry_id"`
	Sig     []byte `json:"sig"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createImage, arg.Uri, arg.EntryID, arg.Sig)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createNgram = `-- name: CreateNgram :exec
INSERT OR REPLACE INTO ngram (image_id, word) VALUES (?, ?)
`

type CreateNgramParams struct {
	ImageID int64  `json:"image_id"`
	Word    []byte `json:"word"`
}

func (q *Queries) CreateNgram(ctx context.Context, arg CreateNgramParams) error {
	_, err := q.db.ExecContext(ctx, createNgram, arg.ImageID, arg.Word)
	return err
}

const deleteImagesByEntryID = `-- name: DeleteImagesByEntryID :exec
DELETE FROM images WHERE entry_id = ?
`

func (q *Queries) DeleteImagesByEntryID(ctx context.Context, entryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteImagesByEntryID, entryID)
	return err
}

const deleteNgramsByEntryID = `-- name: DeleteNgramsByEntryID :exec
DELETE FROM ngram WHERE image_id IN (SELECT id FROM images WHERE entry_id = ?)
`

func (q *Queries) DeleteNgramsByEntryID(ctx context.Context, entryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteNgramsByEntryID, entryID)
	return err
}

const deleteNgramsByImageID = `-- name: DeleteNgramsByImageID :exec
DELETE FROM ngram WHERE image_id = ?
`

func (q *Queries) DeleteNgramsByImageID(ctx context.Context, imageID int64) error {
	_, err := q.db.ExecContext(ctx, deleteNgramsByImageID, imageID)
	return err
}

const getImageByURI = `-- name: GetImageByURI :one
SELECT id, uri, entry_id, sig FROM images WHERE uri = ? LIMIT 1
`

func (q *Queries) GetImageByURI(ctx context.Context, uri string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImageByURI, uri)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Uri,
		&i.EntryID,
		&i.Sig,
	)
	return i, err
}

const listImages = `-- name: ListImages :many
SELECT id, uri, entry_id, sig FROM images
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListImagesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListImages(ctx context.Context, arg ListImagesParams) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Uri,
			&i.EntryID,
			&i.Sig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByEntryID = `-- name: ListImagesByEntryID :many
SELECT id, uri, entry_id, sig FROM images WHERE entry_id = ?
`

func (q *Queries) ListImagesByEntryID(ctx context.Context, entryID int64) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesByEntryID, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Uri,
			&i.EntryID,
			&i.Sig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByEntryIDs = `-- name: ListImagesByEntryIDs :many
SELECT id, uri, entry_id, sig FROM images WHERE entry_id IN (/*SLICE:entry_ids*/?)
`

func (q *Queries) ListImagesByEntryIDs(ctx context.Context, entryIds []int64) ([]Image, error) {
	query := listImagesByEntryIDs
	var queryParams []interface{}
	if len(entryIds) > 0 {
		for _, v := range entryIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:entry_ids*/?", strings.Repeat(",?", len(entryIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:entry_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Uri,
			&i.EntryID,
			&i.Sig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSimilarImages = `-- name: ListSimilarImages :many
SELECT
    i.id,
    i.uri,
    i.entry_id,
    COUNT(isw.word) as score
FROM
    images AS i
JOIN 
    ngram AS isw ON i.id = isw.image_id
JOIN 
    ngram AS isw_search ON isw.word = isw_search.word AND isw.image_id != isw_search.image_id
WHERE
    isw_search.image_id = ?
GROUP BY 
    i.id
ORDER BY 
    score DESC
LIMIT ?
`

type ListSimilarImagesParams struct {
	ImageID int64 `json:"image_id"`
	Limit   int64 `json:"limit"`
}

type ListSimilarImagesRow struct {
	ID      int64  `json:"id"`
	Uri     string `json:"uri"`
	EntryID int64  `json:"entry_id"`
	Score   int64  `json:"score"`
}

func (q *Queries) ListSimilarImages(ctx context.Context, arg ListSimilarImagesParams) ([]ListSimilarImagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSimilarImages, arg.ImageID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSimilarImagesRow
	for rows.Next() {
		var i ListSimilarImagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uri,
			&i.EntryID,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSimilarImagesByImageIDs = `-- name: ListSimilarImagesByImageIDs :many
SELECT
    isw_search.image_id AS search_image_id,
    i.id,
    i.uri,
    i.entry_id,
    COUNT(isw.word) as score
FROM
    images AS i
JOIN 
    ngram AS isw ON i.id = isw.image_id
JOIN 
    ngram AS isw_search ON isw.word = isw_search.word AND isw.image_id != isw_search.image_id
WHERE
    isw_search.image_id IN (/*SLICE:image_ids*/?)
GROUP BY 
    isw_search.image_id, i.id
ORDER BY 
    score DESC
`

type ListSimilarImagesByImageIDsRow struct {
	SearchImageID int64  `json:"search_image_id"`
	ID            int64  `json:"id"`
	Uri           string `json:"uri"`
	EntryID       int64  `json:"entry_id"`
	Score         int64  `json:"score"`
}

func (q *Queries) ListSimilarImagesByImageIDs(ctx context.Context, imageIds []int64) ([]ListSimilarImagesByImageIDsRow, error) {
	query := listSimilarImagesByImageIDs
	var queryParams []interface{}
	if len(imageIds) > 0 {
		for _, v := range imageIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:image_ids*/?", strings.Repeat(",?", len(imageIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:image_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSimilarImagesByImageIDsRow
	for rows.Next() {
		var i ListSimilarImagesByImageIDsRow
		if err := rows.Scan(
			&i.SearchImageID,
			&i.ID,
			&i.Uri,
			&i.EntryID,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
