// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package model

import (
	"time"
)

type Entry struct {
	ID            int64     `json:"id"`
	Title         string    `json:"title"`
	Body          string    `json:"body"`
	FormattedBody string    `json:"formatted_body"`
	Path          string    `json:"path"`
	Format        string    `json:"format"`
	Date          string    `json:"date"`
	CreatedAt     time.Time `json:"created_at"`
	ModifiedAt    time.Time `json:"modified_at"`
}

type Image struct {
	ID      int64  `json:"id"`
	Uri     string `json:"uri"`
	EntryID int64  `json:"entry_id"`
	Sig     []byte `json:"sig"`
}

type Ngram struct {
	ImageID int64  `json:"image_id"`
	Word    []byte `json:"word"`
}
