// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package model

import (
	"context"
	"time"
)

type Querier interface {
	CountEntries(ctx context.Context) (int64, error)
	CountEntriesByDate(ctx context.Context, date string) (int64, error)
	CountPendingJobs(ctx context.Context) (int64, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	DeleteRelatedEntriesByEntryID(ctx context.Context, entryID int64) error
	DeleteTFIDFByEntryID(ctx context.Context, entryID int64) error
	EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error)
	FindNextJob(ctx context.Context, runAfter time.Time) (Job, error)
	GetEntryById(ctx context.Context, id int64) (GetEntryByIdRow, error)
	GetEntryByPath(ctx context.Context, path string) (GetEntryByPathRow, error)
	GetJobByID(ctx context.Context, id int64) (Job, error)
	GetJobTypeByID(ctx context.Context, id int64) (JobType, error)
	GetNextEntry(ctx context.Context, createdAt time.Time) (GetNextEntryRow, error)
	GetOrCreateJobType(ctx context.Context, name string) (JobType, error)
	GetPrevEntry(ctx context.Context, createdAt time.Time) (GetPrevEntryRow, error)
	GrabJob(ctx context.Context, arg GrabJobParams) error
	InsertRelatedEntry(ctx context.Context, arg InsertRelatedEntryParams) error
	InsertTFIDF(ctx context.Context, arg InsertTFIDFParams) error
	ListAllEntriesForSitemap(ctx context.Context) ([]ListAllEntriesForSitemapRow, error)
	ListArchiveMonths(ctx context.Context) ([]ListArchiveMonthsRow, error)
	// Note: sqlite3 driver converts DATE to time.Time by default, which is undesirable for
	// date-based logic here (we want YYYY-MM-DD string). We use CAST(date AS TEXT) to
	// ensure string return and we cannot change the schema to TEXT because we reuse
	// existing data files.
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]ListEntriesRow, error)
	ListEntriesByCategory(ctx context.Context, arg ListEntriesByCategoryParams) ([]ListEntriesByCategoryRow, error)
	ListEntriesByDates(ctx context.Context, dates []string) ([]ListEntriesByDatesRow, error)
	ListEntriesByIds(ctx context.Context, ids []int64) ([]ListEntriesByIdsRow, error)
	ListEntriesByYearMonthDay(ctx context.Context, arg ListEntriesByYearMonthDayParams) ([]ListEntriesByYearMonthDayRow, error)
	ListRelatedEntries(ctx context.Context, entryID int64) ([]ListRelatedEntriesRow, error)
	ListUniqueDates(ctx context.Context, arg ListUniqueDatesParams) ([]string, error)
	MarkJobCompleted(ctx context.Context, id int64) error
	MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) error
	UpdateEntry(ctx context.Context, arg UpdateEntryParams) (Entry, error)
}

var _ Querier = (*Queries)(nil)
