// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package model

import (
	"context"
	"time"
)

type Querier interface {
	CountEntries(ctx context.Context) (int64, error)
	GetEntryByPath(ctx context.Context, path string) (Entry, error)
	GetNextEntry(ctx context.Context, createdAt time.Time) (Entry, error)
	GetPrevEntry(ctx context.Context, createdAt time.Time) (Entry, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListEntriesByYearMonthDay(ctx context.Context, arg ListEntriesByYearMonthDayParams) ([]Entry, error)
}

var _ Querier = (*Queries)(nil)
