// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tfidf.sql

package model

import (
	"context"
)

const listRelatedEntries = `-- name: ListRelatedEntries :many
SELECT related_entry_id, score
FROM related_entries
WHERE entry_id = ?
ORDER BY score DESC
LIMIT 5
`

type ListRelatedEntriesRow struct {
	RelatedEntryID int64   `json:"related_entry_id"`
	Score          float64 `json:"score"`
}

func (q *Queries) ListRelatedEntries(ctx context.Context, entryID int64) ([]ListRelatedEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRelatedEntries, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRelatedEntriesRow
	for rows.Next() {
		var i ListRelatedEntriesRow
		if err := rows.Scan(&i.RelatedEntryID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
