// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tfidf.sql

package model

import (
	"context"
)

const deletePostingsByEntryID = `-- name: DeletePostingsByEntryID :exec
DELETE FROM postings WHERE entry_id = ?
`

func (q *Queries) DeletePostingsByEntryID(ctx context.Context, entryID int64) error {
	_, err := q.db.ExecContext(ctx, deletePostingsByEntryID, entryID)
	return err
}

const deleteRelatedEntriesByEntryID = `-- name: DeleteRelatedEntriesByEntryID :exec
DELETE FROM related_entries WHERE entry_id = ?
`

func (q *Queries) DeleteRelatedEntriesByEntryID(ctx context.Context, entryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRelatedEntriesByEntryID, entryID)
	return err
}

const getTermID = `-- name: GetTermID :one
SELECT id FROM terms WHERE term = ?
`

func (q *Queries) GetTermID(ctx context.Context, term string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTermID, term)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPosting = `-- name: InsertPosting :exec
INSERT INTO postings (entry_id, term_id, term_count, tfidf, tfidf_n)
VALUES (?, ?, ?, 0.0, 0.0)
`

type InsertPostingParams struct {
	EntryID   int64 `json:"entry_id"`
	TermID    int64 `json:"term_id"`
	TermCount int64 `json:"term_count"`
}

func (q *Queries) InsertPosting(ctx context.Context, arg InsertPostingParams) error {
	_, err := q.db.ExecContext(ctx, insertPosting, arg.EntryID, arg.TermID, arg.TermCount)
	return err
}

const insertRelatedEntry = `-- name: InsertRelatedEntry :exec
INSERT INTO related_entries (entry_id, related_entry_id, score)
VALUES (?, ?, ?)
`

type InsertRelatedEntryParams struct {
	EntryID        int64   `json:"entry_id"`
	RelatedEntryID int64   `json:"related_entry_id"`
	Score          float64 `json:"score"`
}

func (q *Queries) InsertRelatedEntry(ctx context.Context, arg InsertRelatedEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertRelatedEntry, arg.EntryID, arg.RelatedEntryID, arg.Score)
	return err
}

const insertTerm = `-- name: InsertTerm :exec
INSERT OR IGNORE INTO terms (term) VALUES (?)
`

func (q *Queries) InsertTerm(ctx context.Context, term string) error {
	_, err := q.db.ExecContext(ctx, insertTerm, term)
	return err
}

const listRelatedEntries = `-- name: ListRelatedEntries :many
SELECT related_entry_id, score
FROM related_entries
WHERE entry_id = ?
ORDER BY score DESC
LIMIT 5
`

type ListRelatedEntriesRow struct {
	RelatedEntryID int64   `json:"related_entry_id"`
	Score          float64 `json:"score"`
}

func (q *Queries) ListRelatedEntries(ctx context.Context, entryID int64) ([]ListRelatedEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRelatedEntries, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRelatedEntriesRow
	for rows.Next() {
		var i ListRelatedEntriesRow
		if err := rows.Scan(&i.RelatedEntryID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
