// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tfidf.sql

package model

import (
	"context"
)

const deletePostingsByEntryID = `-- name: DeletePostingsByEntryID :exec
DELETE FROM postings WHERE entry_id = ?
`

func (q *Queries) DeletePostingsByEntryID(ctx context.Context, entryID int64) error {
	_, err := q.db.ExecContext(ctx, deletePostingsByEntryID, entryID)
	return err
}

const deleteRelatedEntriesByEntryID = `-- name: DeleteRelatedEntriesByEntryID :exec
DELETE FROM related_entries WHERE entry_id = ?
`

func (q *Queries) DeleteRelatedEntriesByEntryID(ctx context.Context, entryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRelatedEntriesByEntryID, entryID)
	return err
}

const getAverageSimilarityScore = `-- name: GetAverageSimilarityScore :one
SELECT CAST(COALESCE(avg(score), 0.0) AS REAL) as avg_score FROM related_entries
`

func (q *Queries) GetAverageSimilarityScore(ctx context.Context) (float64, error) {
	row := q.db.QueryRowContext(ctx, getAverageSimilarityScore)
	var avg_score float64
	err := row.Scan(&avg_score)
	return avg_score, err
}

const getTFIDFStats = `-- name: GetTFIDFStats :one
SELECT 
    (SELECT count(*) FROM terms) as total_terms,
    (SELECT count(DISTINCT entry_id) FROM postings) as indexed_entries,
    (SELECT count(*) FROM related_entries) as total_related_pairs,
    (SELECT count(DISTINCT entry_id) FROM related_entries) as entries_with_related
`

type GetTFIDFStatsRow struct {
	TotalTerms         int64 `json:"total_terms"`
	IndexedEntries     int64 `json:"indexed_entries"`
	TotalRelatedPairs  int64 `json:"total_related_pairs"`
	EntriesWithRelated int64 `json:"entries_with_related"`
}

func (q *Queries) GetTFIDFStats(ctx context.Context) (GetTFIDFStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getTFIDFStats)
	var i GetTFIDFStatsRow
	err := row.Scan(
		&i.TotalTerms,
		&i.IndexedEntries,
		&i.TotalRelatedPairs,
		&i.EntriesWithRelated,
	)
	return i, err
}

const getTermID = `-- name: GetTermID :one
SELECT id FROM terms WHERE term = ?
`

func (q *Queries) GetTermID(ctx context.Context, term string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTermID, term)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getTopTermsByDF = `-- name: GetTopTermsByDF :many
;

SELECT t.term, count(p.entry_id) as df
FROM terms t
JOIN postings p ON t.id = p.term_id
GROUP BY t.id
ORDER BY df DESC
LIMIT ?
`

type GetTopTermsByDFRow struct {
	Term string `json:"term"`
	Df   int64  `json:"df"`
}

func (q *Queries) GetTopTermsByDF(ctx context.Context, limit int64) ([]GetTopTermsByDFRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopTermsByDF, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopTermsByDFRow
	for rows.Next() {
		var i GetTopTermsByDFRow
		if err := rows.Scan(&i.Term, &i.Df); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPosting = `-- name: InsertPosting :exec
INSERT INTO postings (entry_id, term_id, term_count, tfidf, tfidf_n)
VALUES (?, ?, ?, 0.0, 0.0)
`

type InsertPostingParams struct {
	EntryID   int64 `json:"entry_id"`
	TermID    int64 `json:"term_id"`
	TermCount int64 `json:"term_count"`
}

func (q *Queries) InsertPosting(ctx context.Context, arg InsertPostingParams) error {
	_, err := q.db.ExecContext(ctx, insertPosting, arg.EntryID, arg.TermID, arg.TermCount)
	return err
}

const insertRelatedEntry = `-- name: InsertRelatedEntry :exec
INSERT INTO related_entries (entry_id, related_entry_id, score)
VALUES (?, ?, ?)
`

type InsertRelatedEntryParams struct {
	EntryID        int64   `json:"entry_id"`
	RelatedEntryID int64   `json:"related_entry_id"`
	Score          float64 `json:"score"`
}

func (q *Queries) InsertRelatedEntry(ctx context.Context, arg InsertRelatedEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertRelatedEntry, arg.EntryID, arg.RelatedEntryID, arg.Score)
	return err
}

const insertTerm = `-- name: InsertTerm :exec
INSERT OR IGNORE INTO terms (term) VALUES (?)
`

func (q *Queries) InsertTerm(ctx context.Context, term string) error {
	_, err := q.db.ExecContext(ctx, insertTerm, term)
	return err
}

const listRelatedEntries = `-- name: ListRelatedEntries :many
SELECT related_entry_id, score
FROM related_entries
WHERE entry_id = ?
ORDER BY score DESC
LIMIT 5
`

type ListRelatedEntriesRow struct {
	RelatedEntryID int64   `json:"related_entry_id"`
	Score          float64 `json:"score"`
}

func (q *Queries) ListRelatedEntries(ctx context.Context, entryID int64) ([]ListRelatedEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRelatedEntries, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRelatedEntriesRow
	for rows.Next() {
		var i ListRelatedEntriesRow
		if err := rows.Scan(&i.RelatedEntryID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
