// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trackbacks.sql

package model

import (
	"context"
	"database/sql"
	"time"
)

const createTrackback = `-- name: CreateTrackback :exec
INSERT INTO trackbacks (entry_id, trackback_entry_id) VALUES (?, ?)
`

type CreateTrackbackParams struct {
	EntryID          sql.NullInt64 `json:"entry_id"`
	TrackbackEntryID sql.NullInt64 `json:"trackback_entry_id"`
}

func (q *Queries) CreateTrackback(ctx context.Context, arg CreateTrackbackParams) error {
	_, err := q.db.ExecContext(ctx, createTrackback, arg.EntryID, arg.TrackbackEntryID)
	return err
}

const deleteTrackbacksBySourceEntryId = `-- name: DeleteTrackbacksBySourceEntryId :exec
DELETE FROM trackbacks WHERE trackback_entry_id = ?
`

func (q *Queries) DeleteTrackbacksBySourceEntryId(ctx context.Context, trackbackEntryID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteTrackbacksBySourceEntryId, trackbackEntryID)
	return err
}

const listTrackbackEntries = `-- name: ListTrackbackEntries :many
SELECT entries.id, entries.title, entries.body, entries.formatted_body, entries.summary, entries.image_url, entries.path, entries.format, entries.date, entries.created_at, entries.modified_at, entries.publish_at, entries.status, CAST(entries.date AS TEXT) AS date FROM entries
INNER JOIN trackbacks ON entries.id = trackbacks.trackback_entry_id
WHERE trackbacks.entry_id = ?
ORDER BY entries.date DESC, entries.created_at DESC
`

type ListTrackbackEntriesRow struct {
	ID            int64        `json:"id"`
	Title         string       `json:"title"`
	Body          string       `json:"body"`
	FormattedBody string       `json:"formatted_body"`
	Summary       string       `json:"summary"`
	ImageUrl      string       `json:"image_url"`
	Path          string       `json:"path"`
	Format        string       `json:"format"`
	Date          string       `json:"date"`
	CreatedAt     time.Time    `json:"created_at"`
	ModifiedAt    time.Time    `json:"modified_at"`
	PublishAt     sql.NullTime `json:"publish_at"`
	Status        string       `json:"status"`
	Date_2        string       `json:"date_2"`
}

func (q *Queries) ListTrackbackEntries(ctx context.Context, entryID sql.NullInt64) ([]ListTrackbackEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTrackbackEntries, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrackbackEntriesRow
	for rows.Next() {
		var i ListTrackbackEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.FormattedBody,
			&i.Summary,
			&i.ImageUrl,
			&i.Path,
			&i.Format,
			&i.Date,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.PublishAt,
			&i.Status,
			&i.Date_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
