// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: worker.sql

package model

import (
	"context"
	"database/sql"
	"time"
)

const countPendingJobs = `-- name: CountPendingJobs :one
SELECT count(*) FROM jobs WHERE status = 'pending'
`

func (q *Queries) CountPendingJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO jobs (job_type_id, arg, uniqkey, max_retries, created_at, run_after, status)
VALUES (?, ?, ?, ?, ?, ?, 'pending')
ON CONFLICT(job_type_id, uniqkey) DO UPDATE SET arg = excluded.arg, run_after = excluded.run_after, status = 'pending', grabbed_at = NULL, retry_count = 0
RETURNING id, job_type_id, arg, uniqkey, retry_count, max_retries, created_at, run_after, grabbed_at, status, error_message
`

type EnqueueJobParams struct {
	JobTypeID  int64          `json:"job_type_id"`
	Arg        string         `json:"arg"`
	Uniqkey    sql.NullString `json:"uniqkey"`
	MaxRetries int64          `json:"max_retries"`
	CreatedAt  time.Time      `json:"created_at"`
	RunAfter   time.Time      `json:"run_after"`
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, enqueueJob,
		arg.JobTypeID,
		arg.Arg,
		arg.Uniqkey,
		arg.MaxRetries,
		arg.CreatedAt,
		arg.RunAfter,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobTypeID,
		&i.Arg,
		&i.Uniqkey,
		&i.RetryCount,
		&i.MaxRetries,
		&i.CreatedAt,
		&i.RunAfter,
		&i.GrabbedAt,
		&i.Status,
		&i.ErrorMessage,
	)
	return i, err
}

const failStuckJobs = `-- name: FailStuckJobs :exec
UPDATE jobs
SET status = 'failed'
WHERE status = 'running'
AND grabbed_at < datetime('now', '-5 minutes')
AND retry_count >= max_retries
`

func (q *Queries) FailStuckJobs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, failStuckJobs)
	return err
}

const findNextJob = `-- name: FindNextJob :one
SELECT id, job_type_id, arg, uniqkey, retry_count, max_retries, created_at, run_after, grabbed_at, status, error_message FROM jobs WHERE status = 'pending' AND run_after <= ? ORDER BY created_at ASC LIMIT 1
`

func (q *Queries) FindNextJob(ctx context.Context, runAfter time.Time) (Job, error) {
	row := q.db.QueryRowContext(ctx, findNextJob, runAfter)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobTypeID,
		&i.Arg,
		&i.Uniqkey,
		&i.RetryCount,
		&i.MaxRetries,
		&i.CreatedAt,
		&i.RunAfter,
		&i.GrabbedAt,
		&i.Status,
		&i.ErrorMessage,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, job_type_id, arg, uniqkey, retry_count, max_retries, created_at, run_after, grabbed_at, status, error_message FROM jobs WHERE id = ? LIMIT 1
`

func (q *Queries) GetJobByID(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobTypeID,
		&i.Arg,
		&i.Uniqkey,
		&i.RetryCount,
		&i.MaxRetries,
		&i.CreatedAt,
		&i.RunAfter,
		&i.GrabbedAt,
		&i.Status,
		&i.ErrorMessage,
	)
	return i, err
}

const getJobTypeByID = `-- name: GetJobTypeByID :one
SELECT id, name FROM job_types WHERE id = ? LIMIT 1
`

func (q *Queries) GetJobTypeByID(ctx context.Context, id int64) (JobType, error) {
	row := q.db.QueryRowContext(ctx, getJobTypeByID, id)
	var i JobType
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getOrCreateJobType = `-- name: GetOrCreateJobType :one
INSERT INTO job_types (name) VALUES (?) ON CONFLICT(name) DO UPDATE SET name = name RETURNING id, name
`

func (q *Queries) GetOrCreateJobType(ctx context.Context, name string) (JobType, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateJobType, name)
	var i JobType
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const grabJob = `-- name: GrabJob :exec
UPDATE jobs SET status = 'running', grabbed_at = ? WHERE id = ?
`

type GrabJobParams struct {
	GrabbedAt sql.NullTime `json:"grabbed_at"`
	ID        int64        `json:"id"`
}

func (q *Queries) GrabJob(ctx context.Context, arg GrabJobParams) error {
	_, err := q.db.ExecContext(ctx, grabJob, arg.GrabbedAt, arg.ID)
	return err
}

const markJobCompleted = `-- name: MarkJobCompleted :exec
DELETE FROM jobs WHERE id = ?
`

func (q *Queries) MarkJobCompleted(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markJobCompleted, id)
	return err
}

const markJobFailed = `-- name: MarkJobFailed :exec
UPDATE jobs SET status = CASE WHEN retry_count + 1 >= max_retries THEN 'failed' ELSE 'pending' END, retry_count = retry_count + 1, run_after = ?, error_message = ?, grabbed_at = NULL WHERE id = ?
`

type MarkJobFailedParams struct {
	RunAfter     time.Time      `json:"run_after"`
	ErrorMessage sql.NullString `json:"error_message"`
	ID           int64          `json:"id"`
}

func (q *Queries) MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) error {
	_, err := q.db.ExecContext(ctx, markJobFailed, arg.RunAfter, arg.ErrorMessage, arg.ID)
	return err
}

const recoverStuckJobs = `-- name: RecoverStuckJobs :exec
UPDATE jobs
SET status = 'pending', grabbed_at = NULL, retry_count = retry_count + 1
WHERE status = 'running'
AND grabbed_at < datetime('now', '-5 minutes')
AND retry_count < max_retries
`

func (q *Queries) RecoverStuckJobs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, recoverStuckJobs)
	return err
}
