// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cache.sql

package cachedb

import (
	"context"
	"database/sql"
	"time"
)

const deleteCache = `-- name: DeleteCache :exec
DELETE FROM cache WHERE cache_key = ?
`

func (q *Queries) DeleteCache(ctx context.Context, cacheKey string) error {
	_, err := q.db.ExecContext(ctx, deleteCache, cacheKey)
	return err
}

const deleteCacheRelationsByCacheKey = `-- name: DeleteCacheRelationsByCacheKey :exec
DELETE FROM cache_relation WHERE cache_key = ?
`

func (q *Queries) DeleteCacheRelationsByCacheKey(ctx context.Context, cacheKey string) error {
	_, err := q.db.ExecContext(ctx, deleteCacheRelationsByCacheKey, cacheKey)
	return err
}

const deleteCacheRelationsBySourceID = `-- name: DeleteCacheRelationsBySourceID :exec
DELETE FROM cache_relation WHERE source_id = ?
`

func (q *Queries) DeleteCacheRelationsBySourceID(ctx context.Context, sourceID string) error {
	_, err := q.db.ExecContext(ctx, deleteCacheRelationsBySourceID, sourceID)
	return err
}

const getCache = `-- name: GetCache :one
SELECT cache_key, content, etag, content_type, created_at FROM cache WHERE cache_key = ?
`

func (q *Queries) GetCache(ctx context.Context, cacheKey string) (Cache, error) {
	row := q.db.QueryRowContext(ctx, getCache, cacheKey)
	var i Cache
	err := row.Scan(
		&i.CacheKey,
		&i.Content,
		&i.Etag,
		&i.ContentType,
		&i.CreatedAt,
	)
	return i, err
}

const getCacheStats = `-- name: GetCacheStats :one
SELECT
    COUNT(*) AS total_count,
    COALESCE(SUM(LENGTH(content)), 0) AS total_size,
    MIN(created_at) AS oldest_at,
    MAX(created_at) AS newest_at
FROM cache
`

type GetCacheStatsRow struct {
	TotalCount int64       `json:"total_count"`
	TotalSize  interface{} `json:"total_size"`
	OldestAt   interface{} `json:"oldest_at"`
	NewestAt   interface{} `json:"newest_at"`
}

func (q *Queries) GetCacheStats(ctx context.Context) (GetCacheStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getCacheStats)
	var i GetCacheStatsRow
	err := row.Scan(
		&i.TotalCount,
		&i.TotalSize,
		&i.OldestAt,
		&i.NewestAt,
	)
	return i, err
}

const getMetadata = `-- name: GetMetadata :one
SELECT value FROM cache_metadata WHERE key = ?
`

func (q *Queries) GetMetadata(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMetadata, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const insertCache = `-- name: InsertCache :exec
INSERT OR REPLACE INTO cache (cache_key, content, etag, content_type)
VALUES (?, ?, ?, ?)
`

type InsertCacheParams struct {
	CacheKey    string `json:"cache_key"`
	Content     []byte `json:"content"`
	Etag        string `json:"etag"`
	ContentType string `json:"content_type"`
}

func (q *Queries) InsertCache(ctx context.Context, arg InsertCacheParams) error {
	_, err := q.db.ExecContext(ctx, insertCache,
		arg.CacheKey,
		arg.Content,
		arg.Etag,
		arg.ContentType,
	)
	return err
}

const insertCacheRelation = `-- name: InsertCacheRelation :exec
INSERT INTO cache_relation (cache_key, source_id)
VALUES (?, ?)
`

type InsertCacheRelationParams struct {
	CacheKey string `json:"cache_key"`
	SourceID string `json:"source_id"`
}

func (q *Queries) InsertCacheRelation(ctx context.Context, arg InsertCacheRelationParams) error {
	_, err := q.db.ExecContext(ctx, insertCacheRelation, arg.CacheKey, arg.SourceID)
	return err
}

const listCacheEntries = `-- name: ListCacheEntries :many
SELECT
    cache_key,
    LENGTH(content) AS size,
    etag,
    content_type,
    created_at
FROM cache
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListCacheEntriesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListCacheEntriesRow struct {
	CacheKey    string        `json:"cache_key"`
	Size        sql.NullInt64 `json:"size"`
	Etag        string        `json:"etag"`
	ContentType string        `json:"content_type"`
	CreatedAt   time.Time     `json:"created_at"`
}

func (q *Queries) ListCacheEntries(ctx context.Context, arg ListCacheEntriesParams) ([]ListCacheEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCacheEntries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCacheEntriesRow
	for rows.Next() {
		var i ListCacheEntriesRow
		if err := rows.Scan(
			&i.CacheKey,
			&i.Size,
			&i.Etag,
			&i.ContentType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetadata = `-- name: ListMetadata :many
SELECT "key", value FROM cache_metadata
`

func (q *Queries) ListMetadata(ctx context.Context) ([]CacheMetadatum, error) {
	rows, err := q.db.QueryContext(ctx, listMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CacheMetadatum
	for rows.Next() {
		var i CacheMetadatum
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMetadata = `-- name: SetMetadata :exec
INSERT OR REPLACE INTO cache_metadata (key, value) VALUES (?, ?)
`

type SetMetadataParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetMetadata(ctx context.Context, arg SetMetadataParams) error {
	_, err := q.db.ExecContext(ctx, setMetadata, arg.Key, arg.Value)
	return err
}

const truncateCache = `-- name: TruncateCache :exec
DELETE FROM cache
`

func (q *Queries) TruncateCache(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, truncateCache)
	return err
}

const updateCacheContentToNull = `-- name: UpdateCacheContentToNull :exec
UPDATE cache SET content = NULL WHERE cache_key = ?
`

func (q *Queries) UpdateCacheContentToNull(ctx context.Context, cacheKey string) error {
	_, err := q.db.ExecContext(ctx, updateCacheContentToNull, cacheKey)
	return err
}
