// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cache.sql

package cachedb

import (
	"context"
)

const deleteCache = `-- name: DeleteCache :exec
DELETE FROM cache WHERE cache_key = ?
`

func (q *Queries) DeleteCache(ctx context.Context, cacheKey string) error {
	_, err := q.db.ExecContext(ctx, deleteCache, cacheKey)
	return err
}

const deleteCacheRelationsByCacheKey = `-- name: DeleteCacheRelationsByCacheKey :exec
DELETE FROM cache_relation WHERE cache_key = ?
`

func (q *Queries) DeleteCacheRelationsByCacheKey(ctx context.Context, cacheKey string) error {
	_, err := q.db.ExecContext(ctx, deleteCacheRelationsByCacheKey, cacheKey)
	return err
}

const deleteCacheRelationsBySourceID = `-- name: DeleteCacheRelationsBySourceID :exec
DELETE FROM cache_relation WHERE source_id = ?
`

func (q *Queries) DeleteCacheRelationsBySourceID(ctx context.Context, sourceID string) error {
	_, err := q.db.ExecContext(ctx, deleteCacheRelationsBySourceID, sourceID)
	return err
}

const getCache = `-- name: GetCache :one
SELECT content FROM cache WHERE cache_key = ?
`

func (q *Queries) GetCache(ctx context.Context, cacheKey string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getCache, cacheKey)
	var content []byte
	err := row.Scan(&content)
	return content, err
}

const insertCache = `-- name: InsertCache :exec
INSERT OR REPLACE INTO cache (cache_key, content)
VALUES (?, ?)
`

type InsertCacheParams struct {
	CacheKey string `json:"cache_key"`
	Content  []byte `json:"content"`
}

func (q *Queries) InsertCache(ctx context.Context, arg InsertCacheParams) error {
	_, err := q.db.ExecContext(ctx, insertCache, arg.CacheKey, arg.Content)
	return err
}

const insertCacheRelation = `-- name: InsertCacheRelation :exec
INSERT INTO cache_relation (cache_key, source_id)
VALUES (?, ?)
`

type InsertCacheRelationParams struct {
	CacheKey string `json:"cache_key"`
	SourceID string `json:"source_id"`
}

func (q *Queries) InsertCacheRelation(ctx context.Context, arg InsertCacheRelationParams) error {
	_, err := q.db.ExecContext(ctx, insertCacheRelation, arg.CacheKey, arg.SourceID)
	return err
}
