// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package cachedb

type Cache struct {
	CacheKey string `json:"cache_key"`
	Content  []byte `json:"content"`
}

type CacheRelation struct {
	ID       int64  `json:"id"`
	CacheKey string `json:"cache_key"`
	SourceID string `json:"source_id"`
}
