// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package cachedb

import (
	"time"
)

type Cache struct {
	CacheKey    string    `json:"cache_key"`
	Content     []byte    `json:"content"`
	Etag        string    `json:"etag"`
	ContentType string    `json:"content_type"`
	CreatedAt   time.Time `json:"created_at"`
}

type CacheMetadatum struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type CacheRelation struct {
	ID       int64  `json:"id"`
	CacheKey string `json:"cache_key"`
	SourceID string `json:"source_id"`
}
