// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package cachedb

import (
	"context"
)

type Querier interface {
	DeleteCache(ctx context.Context, cacheKey string) error
	DeleteCacheRelationsByCacheKey(ctx context.Context, cacheKey string) error
	DeleteCacheRelationsBySourceID(ctx context.Context, sourceID string) error
	GetCache(ctx context.Context, cacheKey string) ([]byte, error)
	InsertCache(ctx context.Context, arg InsertCacheParams) error
	InsertCacheRelation(ctx context.Context, arg InsertCacheRelationParams) error
}

var _ Querier = (*Queries)(nil)
