// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package cachedb

import (
	"context"
)

type Querier interface {
	DeleteCache(ctx context.Context, cacheKey string) error
	DeleteCacheRelationsByCacheKey(ctx context.Context, cacheKey string) error
	DeleteCacheRelationsBySourceID(ctx context.Context, sourceID string) error
	GetCache(ctx context.Context, cacheKey string) (Cache, error)
	GetCacheStats(ctx context.Context) (GetCacheStatsRow, error)
	GetMetadata(ctx context.Context, key string) (string, error)
	InsertCache(ctx context.Context, arg InsertCacheParams) error
	InsertCacheRelation(ctx context.Context, arg InsertCacheRelationParams) error
	ListCacheEntries(ctx context.Context, arg ListCacheEntriesParams) ([]ListCacheEntriesRow, error)
	ListMetadata(ctx context.Context) ([]CacheMetadatum, error)
	SetMetadata(ctx context.Context, arg SetMetadataParams) error
	TruncateCache(ctx context.Context) error
	UpdateCacheContentToNull(ctx context.Context, cacheKey string) error
}

var _ Querier = (*Queries)(nil)
