// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package workerdb

import (
	"context"
	"time"
)

type Querier interface {
	CountJobs(ctx context.Context) (int64, error)
	CountPendingJobs(ctx context.Context) (int64, error)
	EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error)
	FailStuckJobs(ctx context.Context) error
	FindNextJob(ctx context.Context, runAfter time.Time) (Job, error)
	GetJobByID(ctx context.Context, id int64) (Job, error)
	GetJobTypeByID(ctx context.Context, id int64) (JobType, error)
	GetOrCreateJobType(ctx context.Context, name string) (JobType, error)
	GrabJob(ctx context.Context, arg GrabJobParams) error
	ListJobs(ctx context.Context, arg ListJobsParams) ([]ListJobsRow, error)
	MarkJobCompleted(ctx context.Context, id int64) error
	MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) error
	RecoverStuckJobs(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
