// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: worker.sql

package workerdb

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const cleanupJobs = `-- name: CleanupJobs :exec
DELETE FROM jobs WHERE status = 'completed' AND finished_at < ?
`

func (q *Queries) CleanupJobs(ctx context.Context, finishedAt sql.NullTime) error {
	_, err := q.db.ExecContext(ctx, cleanupJobs, finishedAt)
	return err
}

const countJobs = `-- name: CountJobs :one
SELECT count(*) FROM jobs
`

func (q *Queries) CountJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingJobs = `-- name: CountPendingJobs :one
SELECT count(*) FROM jobs WHERE status = 'pending'
`

func (q *Queries) CountPendingJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO jobs (job_type_id, arg, uniqkey, max_retries, created_at, run_after, status, depends_on)
VALUES (?, ?, ?, ?, ?, ?, 'pending', ?)
RETURNING id, job_type_id, arg, uniqkey, retry_count, max_retries, created_at, run_after, grabbed_at, status, error_message, depends_on, finished_at
`

type EnqueueJobParams struct {
	JobTypeID  int64          `json:"job_type_id"`
	Arg        string         `json:"arg"`
	Uniqkey    sql.NullString `json:"uniqkey"`
	MaxRetries int64          `json:"max_retries"`
	CreatedAt  time.Time      `json:"created_at"`
	RunAfter   time.Time      `json:"run_after"`
	DependsOn  sql.NullString `json:"depends_on"`
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, enqueueJob,
		arg.JobTypeID,
		arg.Arg,
		arg.Uniqkey,
		arg.MaxRetries,
		arg.CreatedAt,
		arg.RunAfter,
		arg.DependsOn,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobTypeID,
		&i.Arg,
		&i.Uniqkey,
		&i.RetryCount,
		&i.MaxRetries,
		&i.CreatedAt,
		&i.RunAfter,
		&i.GrabbedAt,
		&i.Status,
		&i.ErrorMessage,
		&i.DependsOn,
		&i.FinishedAt,
	)
	return i, err
}

const failStuckJobs = `-- name: FailStuckJobs :exec
UPDATE jobs
SET status = 'failed'
WHERE status = 'running'
AND grabbed_at < datetime('now', '-5 minutes')
AND retry_count >= max_retries
`

func (q *Queries) FailStuckJobs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, failStuckJobs)
	return err
}

const findNextJob = `-- name: FindNextJob :one
SELECT id, job_type_id, arg, uniqkey, retry_count, max_retries, created_at, run_after, grabbed_at, status, error_message, depends_on, finished_at FROM jobs WHERE status = 'pending' AND run_after <= ? ORDER BY created_at ASC LIMIT 1
`

func (q *Queries) FindNextJob(ctx context.Context, runAfter time.Time) (Job, error) {
	row := q.db.QueryRowContext(ctx, findNextJob, runAfter)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobTypeID,
		&i.Arg,
		&i.Uniqkey,
		&i.RetryCount,
		&i.MaxRetries,
		&i.CreatedAt,
		&i.RunAfter,
		&i.GrabbedAt,
		&i.Status,
		&i.ErrorMessage,
		&i.DependsOn,
		&i.FinishedAt,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, job_type_id, arg, uniqkey, retry_count, max_retries, created_at, run_after, grabbed_at, status, error_message, depends_on, finished_at FROM jobs WHERE id = ? LIMIT 1
`

func (q *Queries) GetJobByID(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobTypeID,
		&i.Arg,
		&i.Uniqkey,
		&i.RetryCount,
		&i.MaxRetries,
		&i.CreatedAt,
		&i.RunAfter,
		&i.GrabbedAt,
		&i.Status,
		&i.ErrorMessage,
		&i.DependsOn,
		&i.FinishedAt,
	)
	return i, err
}

const getJobByTypeAndUniqkey = `-- name: GetJobByTypeAndUniqkey :one
SELECT id, job_type_id, arg, uniqkey, retry_count, max_retries, created_at, run_after, grabbed_at, status, error_message, depends_on, finished_at FROM jobs WHERE job_type_id = ? AND uniqkey = ? LIMIT 1
`

type GetJobByTypeAndUniqkeyParams struct {
	JobTypeID int64          `json:"job_type_id"`
	Uniqkey   sql.NullString `json:"uniqkey"`
}

func (q *Queries) GetJobByTypeAndUniqkey(ctx context.Context, arg GetJobByTypeAndUniqkeyParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobByTypeAndUniqkey, arg.JobTypeID, arg.Uniqkey)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobTypeID,
		&i.Arg,
		&i.Uniqkey,
		&i.RetryCount,
		&i.MaxRetries,
		&i.CreatedAt,
		&i.RunAfter,
		&i.GrabbedAt,
		&i.Status,
		&i.ErrorMessage,
		&i.DependsOn,
		&i.FinishedAt,
	)
	return i, err
}

const getJobTypeByID = `-- name: GetJobTypeByID :one
SELECT id, name FROM job_types WHERE id = ? LIMIT 1
`

func (q *Queries) GetJobTypeByID(ctx context.Context, id int64) (JobType, error) {
	row := q.db.QueryRowContext(ctx, getJobTypeByID, id)
	var i JobType
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getJobsByIDs = `-- name: GetJobsByIDs :many
SELECT id, job_type_id, arg, uniqkey, retry_count, max_retries, created_at, run_after, grabbed_at, status, error_message, depends_on, finished_at FROM jobs WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) GetJobsByIDs(ctx context.Context, ids []int64) ([]Job, error) {
	query := getJobsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.JobTypeID,
			&i.Arg,
			&i.Uniqkey,
			&i.RetryCount,
			&i.MaxRetries,
			&i.CreatedAt,
			&i.RunAfter,
			&i.GrabbedAt,
			&i.Status,
			&i.ErrorMessage,
			&i.DependsOn,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrCreateJobType = `-- name: GetOrCreateJobType :one
INSERT INTO job_types (name) VALUES (?) ON CONFLICT(name) DO UPDATE SET name = name RETURNING id, name
`

func (q *Queries) GetOrCreateJobType(ctx context.Context, name string) (JobType, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateJobType, name)
	var i JobType
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const grabJob = `-- name: GrabJob :execresult
UPDATE jobs SET status = 'running', grabbed_at = ?1
WHERE id = ?2 AND status = 'pending'
`

type GrabJobParams struct {
	GrabbedAt sql.NullTime `json:"grabbed_at"`
	ID        int64        `json:"id"`
}

func (q *Queries) GrabJob(ctx context.Context, arg GrabJobParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, grabJob, arg.GrabbedAt, arg.ID)
}

const listJobs = `-- name: ListJobs :many
SELECT 
    j.id, 
    j.job_type_id, 
    j.arg, 
    j.uniqkey, 
    j.retry_count, 
    j.max_retries, 
    j.created_at, 
    j.run_after, 
    j.grabbed_at, 
    j.status, 
    j.error_message, 
    j.depends_on, 
    j.finished_at,
    jt.name as job_type_name
FROM jobs j
JOIN job_types jt ON j.job_type_id = jt.id
ORDER BY j.created_at DESC
LIMIT ? OFFSET ?
`

type ListJobsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListJobsRow struct {
	ID           int64          `json:"id"`
	JobTypeID    int64          `json:"job_type_id"`
	Arg          string         `json:"arg"`
	Uniqkey      sql.NullString `json:"uniqkey"`
	RetryCount   int64          `json:"retry_count"`
	MaxRetries   int64          `json:"max_retries"`
	CreatedAt    time.Time      `json:"created_at"`
	RunAfter     time.Time      `json:"run_after"`
	GrabbedAt    sql.NullTime   `json:"grabbed_at"`
	Status       string         `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
	DependsOn    sql.NullString `json:"depends_on"`
	FinishedAt   sql.NullTime   `json:"finished_at"`
	JobTypeName  string         `json:"job_type_name"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]ListJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsRow
	for rows.Next() {
		var i ListJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.JobTypeID,
			&i.Arg,
			&i.Uniqkey,
			&i.RetryCount,
			&i.MaxRetries,
			&i.CreatedAt,
			&i.RunAfter,
			&i.GrabbedAt,
			&i.Status,
			&i.ErrorMessage,
			&i.DependsOn,
			&i.FinishedAt,
			&i.JobTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobCompleted = `-- name: MarkJobCompleted :exec
UPDATE jobs
SET
    status = CASE WHEN created_at > grabbed_at THEN 'pending' ELSE 'completed' END,
    finished_at = CASE WHEN created_at > grabbed_at THEN NULL ELSE ? END,
    grabbed_at = NULL,
    retry_count = CASE WHEN created_at > grabbed_at THEN 0 ELSE retry_count END
WHERE id = ?
`

type MarkJobCompletedParams struct {
	FinishedAt sql.NullTime `json:"finished_at"`
	ID         int64        `json:"id"`
}

func (q *Queries) MarkJobCompleted(ctx context.Context, arg MarkJobCompletedParams) error {
	_, err := q.db.ExecContext(ctx, markJobCompleted, arg.FinishedAt, arg.ID)
	return err
}

const markJobFailed = `-- name: MarkJobFailed :exec
UPDATE jobs SET status = CASE WHEN retry_count + 1 >= max_retries THEN 'failed' ELSE 'pending' END, retry_count = retry_count + 1, run_after = ?, error_message = ?, grabbed_at = NULL WHERE id = ?
`

type MarkJobFailedParams struct {
	RunAfter     time.Time      `json:"run_after"`
	ErrorMessage sql.NullString `json:"error_message"`
	ID           int64          `json:"id"`
}

func (q *Queries) MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) error {
	_, err := q.db.ExecContext(ctx, markJobFailed, arg.RunAfter, arg.ErrorMessage, arg.ID)
	return err
}

const markJobPermanentlyFailed = `-- name: MarkJobPermanentlyFailed :exec
UPDATE jobs SET status = 'failed', error_message = ?, grabbed_at = NULL, finished_at = ? WHERE id = ?
`

type MarkJobPermanentlyFailedParams struct {
	ErrorMessage sql.NullString `json:"error_message"`
	FinishedAt   sql.NullTime   `json:"finished_at"`
	ID           int64          `json:"id"`
}

func (q *Queries) MarkJobPermanentlyFailed(ctx context.Context, arg MarkJobPermanentlyFailedParams) error {
	_, err := q.db.ExecContext(ctx, markJobPermanentlyFailed, arg.ErrorMessage, arg.FinishedAt, arg.ID)
	return err
}

const recoverStuckJobs = `-- name: RecoverStuckJobs :exec
UPDATE jobs
SET status = 'pending', grabbed_at = NULL, retry_count = retry_count + 1
WHERE status = 'running'
AND grabbed_at < datetime('now', '-5 minutes')
AND retry_count < max_retries
`

func (q *Queries) RecoverStuckJobs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, recoverStuckJobs)
	return err
}

const updateJobForEnqueue = `-- name: UpdateJobForEnqueue :exec
UPDATE jobs
SET arg = ?,
    depends_on = ?,
    run_after = ?,
    status = CASE WHEN status = 'running' THEN 'running' ELSE 'pending' END,
    retry_count = 0,
    created_at = ?
WHERE id = ?
`

type UpdateJobForEnqueueParams struct {
	Arg       string         `json:"arg"`
	DependsOn sql.NullString `json:"depends_on"`
	RunAfter  time.Time      `json:"run_after"`
	CreatedAt time.Time      `json:"created_at"`
	ID        int64          `json:"id"`
}

func (q *Queries) UpdateJobForEnqueue(ctx context.Context, arg UpdateJobForEnqueueParams) error {
	_, err := q.db.ExecContext(ctx, updateJobForEnqueue,
		arg.Arg,
		arg.DependsOn,
		arg.RunAfter,
		arg.CreatedAt,
		arg.ID,
	)
	return err
}

const updateJobRunAfter = `-- name: UpdateJobRunAfter :exec
UPDATE jobs SET run_after = ? WHERE id = ?
`

type UpdateJobRunAfterParams struct {
	RunAfter time.Time `json:"run_after"`
	ID       int64     `json:"id"`
}

func (q *Queries) UpdateJobRunAfter(ctx context.Context, arg UpdateJobRunAfterParams) error {
	_, err := q.db.ExecContext(ctx, updateJobRunAfter, arg.RunAfter, arg.ID)
	return err
}
