// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package tfidfdb

import (
	"database/sql"
)

type Posting struct {
	ID        int64   `json:"id"`
	EntryID   int64   `json:"entry_id"`
	TermID    int64   `json:"term_id"`
	TermCount int64   `json:"term_count"`
	Tfidf     float64 `json:"tfidf"`
	TfidfN    float64 `json:"tfidf_n"`
}

type RelatedEntry struct {
	ID             int64   `json:"id"`
	EntryID        int64   `json:"entry_id"`
	RelatedEntryID int64   `json:"related_entry_id"`
	Score          float64 `json:"score"`
}

type Term struct {
	ID           int64         `json:"id"`
	Term         string        `json:"term"`
	DfCount      int64         `json:"df_count"`
	FirstEntryID sql.NullInt64 `json:"first_entry_id"`
}
