// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package tfidfdb

import (
	"database/sql"
	"time"
)

type Entry struct {
	ID            int64        `json:"id"`
	Title         string       `json:"title"`
	Body          string       `json:"body"`
	FormattedBody string       `json:"formatted_body"`
	Summary       string       `json:"summary"`
	ImageUrl      string       `json:"image_url"`
	Path          string       `json:"path"`
	Format        string       `json:"format"`
	Date          string       `json:"date"`
	CreatedAt     time.Time    `json:"created_at"`
	ModifiedAt    time.Time    `json:"modified_at"`
	PublishAt     sql.NullTime `json:"publish_at"`
	Status        string       `json:"status"`
}

type Exif struct {
	Uri         string         `json:"uri"`
	OriginalUri sql.NullString `json:"original_uri"`
	Model       sql.NullString `json:"model"`
	Make        sql.NullString `json:"make"`
	Focallength sql.NullString `json:"focallength"`
	Fnumber     sql.NullString `json:"fnumber"`
	Iso         sql.NullString `json:"iso"`
	Speed       sql.NullString `json:"speed"`
}

type Posting struct {
	ID        int64   `json:"id"`
	EntryID   int64   `json:"entry_id"`
	TermID    int64   `json:"term_id"`
	TermCount int64   `json:"term_count"`
	Tfidf     float64 `json:"tfidf"`
	TfidfN    float64 `json:"tfidf_n"`
}

type RelatedEntry struct {
	ID             int64   `json:"id"`
	EntryID        int64   `json:"entry_id"`
	RelatedEntryID int64   `json:"related_entry_id"`
	Score          float64 `json:"score"`
}

type Term struct {
	ID           int64         `json:"id"`
	Term         string        `json:"term"`
	DfCount      int64         `json:"df_count"`
	FirstEntryID sql.NullInt64 `json:"first_entry_id"`
}

type Trackback struct {
	ID               int64         `json:"id"`
	EntryID          sql.NullInt64 `json:"entry_id"`
	TrackbackEntryID sql.NullInt64 `json:"trackback_entry_id"`
}
