// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package tfidfdb

import (
	"context"
	"database/sql"
)

type Querier interface {
	DecrementTermDFCount(ctx context.Context, id int64) error
	DeletePostingsByEntryID(ctx context.Context, entryID int64) error
	DeleteRelatedEntriesByEntryID(ctx context.Context, entryID int64) error
	GetAverageSimilarityScore(ctx context.Context) (float64, error)
	GetTFIDFStats(ctx context.Context) (GetTFIDFStatsRow, error)
	GetTermByTerm(ctx context.Context, term string) (Term, error)
	GetTermIDsByEntryID(ctx context.Context, entryID int64) ([]int64, error)
	GetTermsByFirstEntryID(ctx context.Context, firstEntryID sql.NullInt64) ([]Term, error)
	GetTopTermsByDF(ctx context.Context, limit int64) ([]GetTopTermsByDFRow, error)
	InsertPosting(ctx context.Context, arg InsertPostingParams) error
	InsertRelatedEntry(ctx context.Context, arg InsertRelatedEntryParams) error
	ListRelatedEntries(ctx context.Context, entryID int64) ([]ListRelatedEntriesRow, error)
	ListRelatedEntriesByEntryIDs(ctx context.Context, entryIds []int64) ([]ListRelatedEntriesByEntryIDsRow, error)
	UpsertTerm(ctx context.Context, arg UpsertTermParams) (Term, error)
}

var _ Querier = (*Queries)(nil)
