// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tfidf.sql

package tfidfdb

import (
	"context"
	"database/sql"
	"strings"
)

const decrementTermDFCount = `-- name: DecrementTermDFCount :exec
UPDATE terms SET df_count = df_count - 1 WHERE id = ?
`

func (q *Queries) DecrementTermDFCount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, decrementTermDFCount, id)
	return err
}

const deletePostingsByEntryID = `-- name: DeletePostingsByEntryID :exec
DELETE FROM postings WHERE entry_id = ?
`

func (q *Queries) DeletePostingsByEntryID(ctx context.Context, entryID int64) error {
	_, err := q.db.ExecContext(ctx, deletePostingsByEntryID, entryID)
	return err
}

const deleteRelatedEntriesByEntryID = `-- name: DeleteRelatedEntriesByEntryID :exec
DELETE FROM related_entries WHERE entry_id = ?
`

func (q *Queries) DeleteRelatedEntriesByEntryID(ctx context.Context, entryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRelatedEntriesByEntryID, entryID)
	return err
}

const getAverageSimilarityScore = `-- name: GetAverageSimilarityScore :one
SELECT CAST(COALESCE(avg(score), 0.0) AS REAL) as avg_score FROM related_entries
`

func (q *Queries) GetAverageSimilarityScore(ctx context.Context) (float64, error) {
	row := q.db.QueryRowContext(ctx, getAverageSimilarityScore)
	var avg_score float64
	err := row.Scan(&avg_score)
	return avg_score, err
}

const getTFIDFStats = `-- name: GetTFIDFStats :one
SELECT 
    (SELECT count(*) FROM terms) as total_terms,
    (SELECT count(DISTINCT entry_id) FROM postings) as indexed_entries,
    (SELECT count(*) FROM related_entries) as total_related_pairs,
    (SELECT count(DISTINCT entry_id) FROM related_entries) as entries_with_related
`

type GetTFIDFStatsRow struct {
	TotalTerms         int64 `json:"total_terms"`
	IndexedEntries     int64 `json:"indexed_entries"`
	TotalRelatedPairs  int64 `json:"total_related_pairs"`
	EntriesWithRelated int64 `json:"entries_with_related"`
}

func (q *Queries) GetTFIDFStats(ctx context.Context) (GetTFIDFStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getTFIDFStats)
	var i GetTFIDFStatsRow
	err := row.Scan(
		&i.TotalTerms,
		&i.IndexedEntries,
		&i.TotalRelatedPairs,
		&i.EntriesWithRelated,
	)
	return i, err
}

const getTermByTerm = `-- name: GetTermByTerm :one
SELECT id, term, df_count, first_entry_id FROM terms WHERE term = ?
`

func (q *Queries) GetTermByTerm(ctx context.Context, term string) (Term, error) {
	row := q.db.QueryRowContext(ctx, getTermByTerm, term)
	var i Term
	err := row.Scan(
		&i.ID,
		&i.Term,
		&i.DfCount,
		&i.FirstEntryID,
	)
	return i, err
}

const getTermIDsByEntryID = `-- name: GetTermIDsByEntryID :many
SELECT term_id FROM postings WHERE entry_id = ?
`

func (q *Queries) GetTermIDsByEntryID(ctx context.Context, entryID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getTermIDsByEntryID, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var term_id int64
		if err := rows.Scan(&term_id); err != nil {
			return nil, err
		}
		items = append(items, term_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTermsByFirstEntryID = `-- name: GetTermsByFirstEntryID :many
SELECT id, term, df_count, first_entry_id FROM terms WHERE first_entry_id = ?
`

func (q *Queries) GetTermsByFirstEntryID(ctx context.Context, firstEntryID sql.NullInt64) ([]Term, error) {
	rows, err := q.db.QueryContext(ctx, getTermsByFirstEntryID, firstEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Term
	for rows.Next() {
		var i Term
		if err := rows.Scan(
			&i.ID,
			&i.Term,
			&i.DfCount,
			&i.FirstEntryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopTermsByDF = `-- name: GetTopTermsByDF :many
;

SELECT term, df_count as df
FROM terms
ORDER BY df_count DESC
LIMIT ?
`

type GetTopTermsByDFRow struct {
	Term string `json:"term"`
	Df   int64  `json:"df"`
}

func (q *Queries) GetTopTermsByDF(ctx context.Context, limit int64) ([]GetTopTermsByDFRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopTermsByDF, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopTermsByDFRow
	for rows.Next() {
		var i GetTopTermsByDFRow
		if err := rows.Scan(&i.Term, &i.Df); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPosting = `-- name: InsertPosting :exec
INSERT INTO postings (entry_id, term_id, term_count, tfidf, tfidf_n)
VALUES (?, ?, ?, 0.0, 0.0)
ON CONFLICT(entry_id, term_id) DO UPDATE SET
    term_count = excluded.term_count
`

type InsertPostingParams struct {
	EntryID   int64 `json:"entry_id"`
	TermID    int64 `json:"term_id"`
	TermCount int64 `json:"term_count"`
}

func (q *Queries) InsertPosting(ctx context.Context, arg InsertPostingParams) error {
	_, err := q.db.ExecContext(ctx, insertPosting, arg.EntryID, arg.TermID, arg.TermCount)
	return err
}

const insertRelatedEntry = `-- name: InsertRelatedEntry :exec
INSERT INTO related_entries (entry_id, related_entry_id, score)
VALUES (?, ?, ?)
`

type InsertRelatedEntryParams struct {
	EntryID        int64   `json:"entry_id"`
	RelatedEntryID int64   `json:"related_entry_id"`
	Score          float64 `json:"score"`
}

func (q *Queries) InsertRelatedEntry(ctx context.Context, arg InsertRelatedEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertRelatedEntry, arg.EntryID, arg.RelatedEntryID, arg.Score)
	return err
}

const listRelatedEntries = `-- name: ListRelatedEntries :many
SELECT related_entry_id, score
FROM related_entries
WHERE entry_id = ?
ORDER BY score DESC
LIMIT 5
`

type ListRelatedEntriesRow struct {
	RelatedEntryID int64   `json:"related_entry_id"`
	Score          float64 `json:"score"`
}

func (q *Queries) ListRelatedEntries(ctx context.Context, entryID int64) ([]ListRelatedEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRelatedEntries, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRelatedEntriesRow
	for rows.Next() {
		var i ListRelatedEntriesRow
		if err := rows.Scan(&i.RelatedEntryID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelatedEntriesByEntryIDs = `-- name: ListRelatedEntriesByEntryIDs :many
SELECT entry_id, related_entry_id, score
FROM (
    SELECT entry_id, related_entry_id, score,
           row_number() OVER (PARTITION BY entry_id ORDER BY score DESC) as rn
    FROM related_entries
    WHERE entry_id IN (/*SLICE:entry_ids*/?)
)
WHERE rn <= 5
`

type ListRelatedEntriesByEntryIDsRow struct {
	EntryID        int64   `json:"entry_id"`
	RelatedEntryID int64   `json:"related_entry_id"`
	Score          float64 `json:"score"`
}

func (q *Queries) ListRelatedEntriesByEntryIDs(ctx context.Context, entryIds []int64) ([]ListRelatedEntriesByEntryIDsRow, error) {
	query := listRelatedEntriesByEntryIDs
	var queryParams []interface{}
	if len(entryIds) > 0 {
		for _, v := range entryIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:entry_ids*/?", strings.Repeat(",?", len(entryIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:entry_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRelatedEntriesByEntryIDsRow
	for rows.Next() {
		var i ListRelatedEntriesByEntryIDsRow
		if err := rows.Scan(&i.EntryID, &i.RelatedEntryID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTerm = `-- name: UpsertTerm :one
INSERT INTO terms (term, df_count, first_entry_id)
VALUES (?, 1, ?)
ON CONFLICT(term) DO UPDATE SET
    df_count = terms.df_count + 1,
    first_entry_id = CASE WHEN terms.df_count <= 0 THEN excluded.first_entry_id ELSE terms.first_entry_id END
RETURNING id, term, df_count, first_entry_id
`

type UpsertTermParams struct {
	Term         string        `json:"term"`
	FirstEntryID sql.NullInt64 `json:"first_entry_id"`
}

func (q *Queries) UpsertTerm(ctx context.Context, arg UpsertTermParams) (Term, error) {
	row := q.db.QueryRowContext(ctx, upsertTerm, arg.Term, arg.FirstEntryID)
	var i Term
	err := row.Scan(
		&i.ID,
		&i.Term,
		&i.DfCount,
		&i.FirstEntryID,
	)
	return i, err
}
