// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package imagesdb

type Image struct {
	ID      int64  `json:"id"`
	Uri     string `json:"uri"`
	EntryID int64  `json:"entry_id"`
	Sig     []byte `json:"sig"`
}

type Ngram struct {
	Word    int64 `json:"word"`
	ImageID int64 `json:"image_id"`
}
