// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package model

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const countAllEntries = `-- name: CountAllEntries :one
SELECT count(*) FROM entries
`

func (q *Queries) CountAllEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEntries = `-- name: CountEntries :one
SELECT count(*) FROM entries WHERE status = 'public' AND (publish_at IS NULL OR publish_at <= CURRENT_TIMESTAMP)
`

func (q *Queries) CountEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
    title, body, formatted_body, summary, image_url, path, format, date, created_at, modified_at, publish_at, status
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12
) RETURNING id, title, body, formatted_body, summary, image_url, path, format, date, created_at, modified_at, publish_at, status
`

type CreateEntryParams struct {
	Title         string       `json:"title"`
	Body          string       `json:"body"`
	FormattedBody string       `json:"formatted_body"`
	Summary       string       `json:"summary"`
	ImageUrl      string       `json:"image_url"`
	Path          string       `json:"path"`
	Format        string       `json:"format"`
	Date          string       `json:"date"`
	CreatedAt     time.Time    `json:"created_at"`
	ModifiedAt    time.Time    `json:"modified_at"`
	PublishAt     sql.NullTime `json:"publish_at"`
	Status        string       `json:"status"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry,
		arg.Title,
		arg.Body,
		arg.FormattedBody,
		arg.Summary,
		arg.ImageUrl,
		arg.Path,
		arg.Format,
		arg.Date,
		arg.CreatedAt,
		arg.ModifiedAt,
		arg.PublishAt,
		arg.Status,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.FormattedBody,
		&i.Summary,
		&i.ImageUrl,
		&i.Path,
		&i.Format,
		&i.Date,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.PublishAt,
		&i.Status,
	)
	return i, err
}

const findScheduledEntriesToPublish = `-- name: FindScheduledEntriesToPublish :many
SELECT id, title, body, formatted_body, summary, image_url, path, format, date, created_at, modified_at, publish_at, status FROM entries
WHERE status IN ('scheduled', 'reserved') AND (publish_at IS NULL OR publish_at <= ?1)
ORDER BY publish_at ASC
`

func (q *Queries) FindScheduledEntriesToPublish(ctx context.Context, now sql.NullTime) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, findScheduledEntriesToPublish, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.FormattedBody,
			&i.Summary,
			&i.ImageUrl,
			&i.Path,
			&i.Format,
			&i.Date,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.PublishAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntryById = `-- name: GetEntryById :one
SELECT id, title, body, formatted_body, summary, image_url, path, format, date, created_at, modified_at, publish_at, status FROM entries
WHERE id = ?1 LIMIT 1
`

func (q *Queries) GetEntryById(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntryById, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.FormattedBody,
		&i.Summary,
		&i.ImageUrl,
		&i.Path,
		&i.Format,
		&i.Date,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.PublishAt,
		&i.Status,
	)
	return i, err
}

const getEntryByPath = `-- name: GetEntryByPath :one
SELECT id, title, body, formatted_body, summary, image_url, path, format, date, created_at, modified_at, publish_at, status FROM entries
WHERE path = ?1 LIMIT 1
`

func (q *Queries) GetEntryByPath(ctx context.Context, path string) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntryByPath, path)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.FormattedBody,
		&i.Summary,
		&i.ImageUrl,
		&i.Path,
		&i.Format,
		&i.Date,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.PublishAt,
		&i.Status,
	)
	return i, err
}

const getNewerEntry = `-- name: GetNewerEntry :one
SELECT id, title, body, formatted_body, summary, image_url, path, format, date, created_at, modified_at, publish_at, status FROM entries
WHERE status = 'public' AND (publish_at IS NULL OR publish_at <= CURRENT_TIMESTAMP) AND created_at > ?1
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetNewerEntry(ctx context.Context, createdAt time.Time) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getNewerEntry, createdAt)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.FormattedBody,
		&i.Summary,
		&i.ImageUrl,
		&i.Path,
		&i.Format,
		&i.Date,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.PublishAt,
		&i.Status,
	)
	return i, err
}

const getOlderEntry = `-- name: GetOlderEntry :one
SELECT id, title, body, formatted_body, summary, image_url, path, format, date, created_at, modified_at, publish_at, status FROM entries
WHERE status = 'public' AND (publish_at IS NULL OR publish_at <= CURRENT_TIMESTAMP) AND created_at < ?1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetOlderEntry(ctx context.Context, createdAt time.Time) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getOlderEntry, createdAt)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.FormattedBody,
		&i.Summary,
		&i.ImageUrl,
		&i.Path,
		&i.Format,
		&i.Date,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.PublishAt,
		&i.Status,
	)
	return i, err
}

const listAllEntries = `-- name: ListAllEntries :many
SELECT id, title, body, formatted_body, summary, image_url, path, format, date, created_at, modified_at, publish_at, status FROM entries
ORDER BY date DESC, created_at DESC
`

func (q *Queries) ListAllEntries(ctx context.Context) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listAllEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.FormattedBody,
			&i.Summary,
			&i.ImageUrl,
			&i.Path,
			&i.Format,
			&i.Date,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.PublishAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllEntriesForSitemap = `-- name: ListAllEntriesForSitemap :many
SELECT path, modified_at FROM entries
WHERE status = 'public' AND (publish_at IS NULL OR publish_at <= CURRENT_TIMESTAMP)
ORDER BY date DESC
`

type ListAllEntriesForSitemapRow struct {
	Path       string    `json:"path"`
	ModifiedAt time.Time `json:"modified_at"`
}

func (q *Queries) ListAllEntriesForSitemap(ctx context.Context) ([]ListAllEntriesForSitemapRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllEntriesForSitemap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllEntriesForSitemapRow
	for rows.Next() {
		var i ListAllEntriesForSitemapRow
		if err := rows.Scan(&i.Path, &i.ModifiedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchiveMonths = `-- name: ListArchiveMonths :many
SELECT
	strftime('%Y', date) as year,
	strftime('%m', date) as month,
	count(*) as count
FROM entries
WHERE status = 'public' AND (publish_at IS NULL OR publish_at <= CURRENT_TIMESTAMP)
GROUP BY strftime('%Y-%m', date)
ORDER BY year DESC, month ASC
`

type ListArchiveMonthsRow struct {
	Year  interface{} `json:"year"`
	Month interface{} `json:"month"`
	Count int64       `json:"count"`
}

func (q *Queries) ListArchiveMonths(ctx context.Context) ([]ListArchiveMonthsRow, error) {
	rows, err := q.db.QueryContext(ctx, listArchiveMonths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArchiveMonthsRow
	for rows.Next() {
		var i ListArchiveMonthsRow
		if err := rows.Scan(&i.Year, &i.Month, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntries = `-- name: ListEntries :many

SELECT id, title, body, formatted_body, summary, image_url, path, format, date, created_at, modified_at, publish_at, status FROM entries
WHERE status = 'public' AND (publish_at IS NULL OR publish_at <= CURRENT_TIMESTAMP) AND date <= ?1
ORDER BY date DESC, created_at ASC
LIMIT ?2
`

type ListEntriesParams struct {
	TargetDate string `json:"target_date"`
	Limit      int64  `json:"limit"`
}

// Note: date column is now TEXT type, so sqlc can map it directly to string without CAST.
func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntries, arg.TargetDate, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.FormattedBody,
			&i.Summary,
			&i.ImageUrl,
			&i.Path,
			&i.Format,
			&i.Date,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.PublishAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesAdmin = `-- name: ListEntriesAdmin :many
SELECT id, title, body, formatted_body, summary, image_url, path, format, date, created_at, modified_at, publish_at, status FROM entries
WHERE (CAST(?1 AS BIGINT) IS NULL OR id < CAST(?1 AS BIGINT))
ORDER BY id DESC
LIMIT ?2
`

type ListEntriesAdminParams struct {
	CursorID sql.NullInt64 `json:"cursor_id"`
	Limit    int64         `json:"limit"`
}

func (q *Queries) ListEntriesAdmin(ctx context.Context, arg ListEntriesAdminParams) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesAdmin, arg.CursorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.FormattedBody,
			&i.Summary,
			&i.ImageUrl,
			&i.Path,
			&i.Format,
			&i.Date,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.PublishAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByCategory = `-- name: ListEntriesByCategory :many
SELECT id, title, body, formatted_body, summary, image_url, path, format, date, created_at, modified_at, publish_at, status FROM entries
WHERE status = 'public' AND (publish_at IS NULL OR publish_at <= CURRENT_TIMESTAMP) AND title LIKE ?1 AND date <= ?2
ORDER BY date DESC, created_at ASC
LIMIT ?3
`

type ListEntriesByCategoryParams struct {
	Title      string `json:"title"`
	TargetDate string `json:"target_date"`
	Limit      int64  `json:"limit"`
}

func (q *Queries) ListEntriesByCategory(ctx context.Context, arg ListEntriesByCategoryParams) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesByCategory, arg.Title, arg.TargetDate, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.FormattedBody,
			&i.Summary,
			&i.ImageUrl,
			&i.Path,
			&i.Format,
			&i.Date,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.PublishAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByDates = `-- name: ListEntriesByDates :many
SELECT id, title, body, formatted_body, summary, image_url, path, format, date, created_at, modified_at, publish_at, status FROM entries
WHERE status = 'public' AND (publish_at IS NULL OR publish_at <= CURRENT_TIMESTAMP) AND date IN (/*SLICE:dates*/?)
ORDER BY date DESC, created_at ASC
`

func (q *Queries) ListEntriesByDates(ctx context.Context, dates []string) ([]Entry, error) {
	query := listEntriesByDates
	var queryParams []interface{}
	if len(dates) > 0 {
		for _, v := range dates {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:dates*/?", strings.Repeat(",?", len(dates))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:dates*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.FormattedBody,
			&i.Summary,
			&i.ImageUrl,
			&i.Path,
			&i.Format,
			&i.Date,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.PublishAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByIds = `-- name: ListEntriesByIds :many
SELECT id, title, body, formatted_body, summary, image_url, path, format, date, created_at, modified_at, publish_at, status FROM entries
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) ListEntriesByIds(ctx context.Context, ids []int64) ([]Entry, error) {
	query := listEntriesByIds
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.FormattedBody,
			&i.Summary,
			&i.ImageUrl,
			&i.Path,
			&i.Format,
			&i.Date,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.PublishAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByYearMonthDay = `-- name: ListEntriesByYearMonthDay :many
SELECT id, title, body, formatted_body, summary, image_url, path, format, date, created_at, modified_at, publish_at, status FROM entries
WHERE status = 'public' AND (publish_at IS NULL OR publish_at <= CURRENT_TIMESTAMP) AND ?1 <= date AND date < ?2
ORDER BY created_at
`

type ListEntriesByYearMonthDayParams struct {
	StartDate string `json:"start_date"`
	EndDate   string `json:"end_date"`
}

func (q *Queries) ListEntriesByYearMonthDay(ctx context.Context, arg ListEntriesByYearMonthDayParams) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesByYearMonthDay, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.FormattedBody,
			&i.Summary,
			&i.ImageUrl,
			&i.Path,
			&i.Format,
			&i.Date,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.PublishAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPathsByDate = `-- name: ListPathsByDate :many
SELECT path FROM entries WHERE date = ?1
`

func (q *Queries) ListPathsByDate(ctx context.Context, date string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPathsByDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUniqueDates = `-- name: ListUniqueDates :many
SELECT DISTINCT date FROM entries
WHERE status = 'public' AND (publish_at IS NULL OR publish_at <= CURRENT_TIMESTAMP) AND date <= ?1
ORDER BY date DESC
LIMIT ?2
`

type ListUniqueDatesParams struct {
	TargetDate string `json:"target_date"`
	Limit      int64  `json:"limit"`
}

func (q *Queries) ListUniqueDates(ctx context.Context, arg ListUniqueDatesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUniqueDates, arg.TargetDate, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var date string
		if err := rows.Scan(&date); err != nil {
			return nil, err
		}
		items = append(items, date)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishEntry = `-- name: PublishEntry :exec
UPDATE entries
SET status = 'public',
    path = ?1,
    date = ?2,
    modified_at = ?3
WHERE id = ?4
`

type PublishEntryParams struct {
	Path       string    `json:"path"`
	Date       string    `json:"date"`
	ModifiedAt time.Time `json:"modified_at"`
	ID         int64     `json:"id"`
}

func (q *Queries) PublishEntry(ctx context.Context, arg PublishEntryParams) error {
	_, err := q.db.ExecContext(ctx, publishEntry,
		arg.Path,
		arg.Date,
		arg.ModifiedAt,
		arg.ID,
	)
	return err
}

const searchEntriesAdmin = `-- name: SearchEntriesAdmin :many
SELECT id, title, body, formatted_body, summary, image_url, path, format, date, created_at, modified_at, publish_at, status FROM entries
WHERE (title LIKE ?1 OR body LIKE ?1)
AND (CAST(?2 AS BIGINT) IS NULL OR id < CAST(?2 AS BIGINT))
ORDER BY id DESC
LIMIT ?3
`

type SearchEntriesAdminParams struct {
	Query    string        `json:"query"`
	CursorID sql.NullInt64 `json:"cursor_id"`
	Limit    int64         `json:"limit"`
}

func (q *Queries) SearchEntriesAdmin(ctx context.Context, arg SearchEntriesAdminParams) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, searchEntriesAdmin, arg.Query, arg.CursorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.FormattedBody,
			&i.Summary,
			&i.ImageUrl,
			&i.Path,
			&i.Format,
			&i.Date,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.PublishAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE entries SET
    title = ?1,
    body = ?2,
    formatted_body = ?3,
    summary = ?4,
    image_url = ?5,
    path = ?6,
    format = ?7,
    date = ?8,
    modified_at = ?9,
    publish_at = ?10,
    status = ?11
WHERE id = ?12
RETURNING id, title, body, formatted_body, summary, image_url, path, format, date, created_at, modified_at, publish_at, status
`

type UpdateEntryParams struct {
	Title         string       `json:"title"`
	Body          string       `json:"body"`
	FormattedBody string       `json:"formatted_body"`
	Summary       string       `json:"summary"`
	ImageUrl      string       `json:"image_url"`
	Path          string       `json:"path"`
	Format        string       `json:"format"`
	Date          string       `json:"date"`
	ModifiedAt    time.Time    `json:"modified_at"`
	PublishAt     sql.NullTime `json:"publish_at"`
	Status        string       `json:"status"`
	ID            int64        `json:"id"`
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, updateEntry,
		arg.Title,
		arg.Body,
		arg.FormattedBody,
		arg.Summary,
		arg.ImageUrl,
		arg.Path,
		arg.Format,
		arg.Date,
		arg.ModifiedAt,
		arg.PublishAt,
		arg.Status,
		arg.ID,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.FormattedBody,
		&i.Summary,
		&i.ImageUrl,
		&i.Path,
		&i.Format,
		&i.Date,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.PublishAt,
		&i.Status,
	)
	return i, err
}
