// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

func Edit(entryJSON string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\"><title>編集</title><link rel=\"preload\" href=\"/js/editor/app-editor.html\" as=\"fetch\"><script src=\"/js/bower_components/webcomponentsjs/webcomponents-lite.min.js\" async></script><link rel=\"shortcut icon\" href=\"/favicon.ico\" type=\"image/x-icon\"><style>\n\t\t@-webkit-keyframes spin{\n\t\t\t0%{-webkit-transform: rotate(0deg);}\n\t\t\t100%{-webkit-transform: rotate(1080deg);}\n\t\t}\n\t\t@keyframes spin{\n\t\t\t0%{transform: rotate(0deg);}\n\t\t\t100%{transform: rotate(1080deg);}\n\t\t}\n\t\t.loading{\n\t\t\tbox-sizing: border-box;\n\t\t\tdisplay: block;\n\t\t\twidth: 36px;\n\t\t\theight: 36px;\n\t\t\tmargin: 100px auto;\n\t\t\tborder-width: 4px;\n\t\t\tborder-style: solid;\n\t\t\tborder-color: transparent #000;\n\t\t\tborder-radius: 18px;\n\t\t\tanimation: spin 2s ease-in-out infinite;\n\t\t}\n\t\t</style></head><body style=\"margin: 0; padding: 0; height: 100vh; width: 100vw; background: #f7f8f9\"><div class=\"loading\"></div><app-editor entry-json=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(entryJSON)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/edit.templ`, Line: 43, Col: 25}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"></app-editor><script>\n\t\t\trequestAnimationFrame(function () {\n\t\t\t\tvar link = document.createElement('link');\n\t\t\t\tlink.rel = \"import\";\n\t\t\t\tlink.href = \"/js/editor/app-editor.html\";\n\t\t\t\tlink.addEventListener('load', function () {\n\t\t\t\t\tvar loading = document.querySelector('.loading');\n\t\t\t\t\tif (loading) loading.parentNode.removeChild(loading);\n\t\t\t\t});\n\t\t\t\tdocument.body.appendChild(link);\n\t\t\t});\n\t\t</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
